import { NextResponse } from 'next/server';
import dbConnect from '@/lib/db';
import DailyChallenge from '@/models/DailyChallenge';
import Question from '@/models/Question';

// GET - Auto-generate daily challenge (Triggered by Vercel Cron)
export async function GET(req) {
    try {
        // Vercel Cron Authentication
        const authHeader = req.headers.get('authorization');
        if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
            return new NextResponse('Unauthorized', {
                status: 401,
            });
        }

        await dbConnect();
        const count = 10;
        const difficulty = 'mixed';

        const targetDate = new Date();
        targetDate.setHours(0, 0, 0, 0); // Sets to midnight of the current day

        // Check if challenge already exists for this date
        const existing = await DailyChallenge.findOne({
            date: { $gte: targetDate, $lt: new Date(targetDate.getTime() + 86400000) }
        });
        
        if (existing) {
            return NextResponse.json({ message: 'Challenge already exists for this date', data: existing }, { status: 400 });
        }

        // Pick random questions
        let query = { isActive: true };
        if (difficulty !== 'mixed') query.difficulty = difficulty;

        const questions = await Question.aggregate([
            { $match: query },
            { $sample: { size: count } }
        ]);

        if (questions.length === 0) {
            return NextResponse.json({ message: 'No questions available in question bank' }, { status: 400 });
        }

        const challengeQuestions = questions.map(q => ({
            questionText: q.questionText,
            options: q.options,
            explanation: q.explanation || '',
            subject: q.subject?.toString() || '',
            difficulty: q.difficulty
        }));

        const challenge = await DailyChallenge.create({
            date: targetDate,
            title: `Daily Challenge - ${targetDate.toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`,
            questions: challengeQuestions,
            duration: count,
            totalMarks: count,
            isAutoGenerated: true,
            status: 'published'
        });

        return NextResponse.json({ success: true, data: challenge }, { status: 201 });
    } catch (error) {
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
