'use client';
import React, { useState, useEffect } from 'react';
import { Target, Plus, Zap, Trash2, Calendar } from 'lucide-react';
import { toast } from 'react-hot-toast';
import Head from 'next/head';
import API from '../../../lib/api';
import Card from '../../../components/ui/Card';
import Loading from '../../../components/Loading';
import AdminRoute from '../../../components/AdminRoute';

const AdminDailyChallenge = () => {
  const [challenges, setChallenges] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [genDate, setGenDate] = useState(new Date().toISOString().split('T')[0]);
  const [genCount, setGenCount] = useState(10);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  const fetchData = async () => {
    try { setLoading(true); const res = await API.request(`/api/admin/daily-challenge?page=${page}&limit=20`); if (res?.success) { setChallenges(res.data || []); setTotalPages(res.pagination?.totalPages || 1); } } catch (e) { } finally { setLoading(false); }
  };
  useEffect(() => { fetchData(); }, [page]);

  const autoGenerate = async () => {
    setGenerating(true);
    try {
      const res = await API.request('/api/admin/daily-challenge/auto-generate', {
        method: 'POST', body: JSON.stringify({ date: genDate, count: genCount })
      });
      if (res?.success) { toast.success('Challenge generated!'); fetchData(); }
      else toast.error(res?.message || 'Failed');
    } catch (e) { toast.error('Failed'); } finally { setGenerating(false); }
  };

  if (loading) return <div className="min-h-screen flex items-center justify-center"><Loading size="md" /></div>;

  return (
    <AdminRoute>
      <div className="min-h-screen pb-24">
        <Head><title>Daily Challenges - Admin</title></Head>
        <div className="container mx-auto py-4 lg:py-8 px-4 space-y-6">
          <h1 className="text-2xl font-black text-slate-900 dark:text-white flex items-center gap-2"><Target className="w-6 h-6 text-primary-500" /> Daily Challenges</h1>

          <Card className="p-4 space-y-3">
            <h2 className="text-sm font-black text-slate-700 dark:text-slate-300">Auto-Generate from Question Bank</h2>
            <div className="flex items-center gap-3 flex-wrap">
              <input type="date" value={genDate} onChange={e => setGenDate(e.target.value)} className="px-3 py-2 border border-slate-200 dark:border-slate-700 rounded-xl text-sm bg-white dark:bg-slate-800 outline-none" />
              <select value={genCount} onChange={e => setGenCount(parseInt(e.target.value))} className="px-3 py-2 border border-slate-200 dark:border-slate-700 rounded-xl text-sm bg-white dark:bg-slate-800 outline-none">
                <option value={5}>5 Questions</option>
                <option value={10}>10 Questions</option>
                <option value={15}>15 Questions</option>
                <option value={20}>20 Questions</option>
              </select>
              <button onClick={autoGenerate} disabled={generating} className="px-4 py-2 bg-primary-500 text-white rounded-xl text-xs font-bold disabled:opacity-50">
                <Zap className="w-3 h-3 inline mr-1" />{generating ? 'Generating...' : 'Generate'}
              </button>
            </div>
          </Card>

          <div className="space-y-2">
            {challenges.map((c, i) => (
              <Card key={c._id || i} className="p-4 flex items-center gap-4">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <Calendar className="w-3 h-3 text-slate-400" />
                    <span className="text-[10px] font-bold text-slate-500">{new Date(c.date).toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' })}</span>
                    <span className={`px-2 py-0.5 rounded text-[9px] font-black ${c.status === 'published' ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-100 text-slate-500'}`}>{c.status}</span>
                    {c.isAutoGenerated && <span className="text-[9px] text-blue-500 font-bold">Auto</span>}
                  </div>
                  <h3 className="text-sm font-bold text-slate-900 dark:text-white">{c.title}</h3>
                  <span className="text-[10px] text-slate-400">{c.questions?.length || 0}Q | {c.totalAttempts} attempts | Avg: {c.avgScore}</span>
                </div>
              </Card>
            ))}
          </div>

          {challenges.length === 0 && <Card className="p-8 text-center"><p className="text-slate-400 font-bold">No challenges created yet</p></Card>}

          {totalPages > 1 && (
            <div className="flex justify-center gap-4">
              <button disabled={page === 1} onClick={() => setPage(page - 1)} className="px-4 py-2 bg-slate-200 rounded-xl text-sm font-bold disabled:opacity-30">Prev</button>
              <span className="text-sm font-bold text-slate-500 py-2">Page {page}/{totalPages}</span>
              <button disabled={page === totalPages} onClick={() => setPage(page + 1)} className="px-4 py-2 bg-slate-200 rounded-xl text-sm font-bold disabled:opacity-30">Next</button>
            </div>
          )}
        </div>
      </div>
    </AdminRoute>
  );
};

export default AdminDailyChallenge;
