import { NextResponse } from 'next/server';
import dbConnect from '@/lib/db';
import DailyChallenge from '@/models/DailyChallenge';
import { pickDailyQuestions, usedDailyQuestionIds, toChallengeQuestions } from '@/lib/utils/dailyQuestionPicker';
import { protect, admin } from '@/middleware/auth';

// POST - Bulk auto-generate daily challenges for a specific month
export async function POST(req) {
    try {
        const auth = await protect(req);
        if (!auth.authenticated || !admin(auth.user)) {
            return NextResponse.json({ message: 'Admin access required' }, { status: 403 });
        }
        await dbConnect();
        const { year, month, count = 10, difficulty = 'mixed' } = await req.json();

        if (!year || month === undefined || month === null) {
            return NextResponse.json({ message: 'Year and month are required' }, { status: 400 });
        }

        const numDays = new Date(year, month + 1, 0).getDate();
        let generatedCount = 0;
        let skippedCount = 0;

        // Questions already used in a challenge (grows as we generate) so no day repeats one
        const used = await usedDailyQuestionIds();

        for (let day = 1; day <= numDays; day++) {
            const targetDate = new Date(year, month, day);
            targetDate.setHours(0, 0, 0, 0);

            // Check if challenge already exists for this date
            const existing = await DailyChallenge.findOne({
                date: { $gte: targetDate, $lt: new Date(targetDate.getTime() + 86400000) }
            }).select('_id').lean();

            if (existing) {
                skippedCount++;
                continue;
            }

            // Clean, image-free questions that already have Hindi, never repeated
            const questions = await pickDailyQuestions({ count, difficulty, exclude: used });

            if (questions.length === 0) {
                return NextResponse.json({ 
                    message: `Stopped at day ${day}: No eligible questions available in question bank`, 
                    generated: generatedCount, 
                    skipped: skippedCount 
                }, { status: 400 });
            }

            // store links into `questions`; the content stays there
            const challengeQuestions = toChallengeQuestions(questions);

            await DailyChallenge.create({
                date: targetDate,
                title: `Daily Challenge - ${targetDate.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}`,
                questions: challengeQuestions,
                duration: challengeQuestions.length,
                totalMarks: challengeQuestions.length,
                isAutoGenerated: true,
                status: 'published'
            });

            generatedCount++;
        }

        return NextResponse.json({ 
            success: true, 
            message: `Successfully generated ${generatedCount} challenges. Skipped ${skippedCount} existing dates.`,
            generated: generatedCount,
            skipped: skippedCount
        }, { status: 201 });

    } catch (error) {
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
