import { NextResponse } from 'next/server';
import dbConnect from '@/lib/db';
import DailyChallenge from '@/models/DailyChallenge';
import Question from '@/models/Question';
import { protect, admin } from '@/middleware/auth';

// POST - Bulk auto-generate daily challenges for a specific month
export async function POST(req) {
    try {
        const auth = await protect(req);
        if (!auth.authenticated || !admin(auth.user)) {
            return NextResponse.json({ message: 'Admin access required' }, { status: 403 });
        }
        await dbConnect();
        const { year, month, count = 10, difficulty = 'mixed' } = await req.json();

        if (!year || month === undefined || month === null) {
            return NextResponse.json({ message: 'Year and month are required' }, { status: 400 });
        }

        const numDays = new Date(year, month + 1, 0).getDate();
        let generatedCount = 0;
        let skippedCount = 0;

        // Base query for random questions
        let query = { isActive: true };
        if (difficulty !== 'mixed') query.difficulty = difficulty;

        for (let day = 1; day <= numDays; day++) {
            const targetDate = new Date(year, month, day);
            targetDate.setHours(0, 0, 0, 0);

            // Check if challenge already exists for this date
            const existing = await DailyChallenge.findOne({
                date: { $gte: targetDate, $lt: new Date(targetDate.getTime() + 86400000) }
            });

            if (existing) {
                skippedCount++;
                continue;
            }

            // Pick random questions for this day
            const questions = await Question.aggregate([
                { $match: query },
                { $sample: { size: count } }
            ]);

            if (questions.length === 0) {
                return NextResponse.json({ 
                    message: `Stopped at day ${day}: No questions available in question bank`, 
                    generated: generatedCount, 
                    skipped: skippedCount 
                }, { status: 400 });
            }

            const challengeQuestions = questions.map(q => ({
                questionText: q.questionText,
                options: q.options,
                explanation: q.explanation || '',
                subject: q.subject?.toString() || '',
                difficulty: q.difficulty
            }));

            await DailyChallenge.create({
                date: targetDate,
                title: `Daily Challenge - ${targetDate.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}`,
                questions: challengeQuestions,
                duration: challengeQuestions.length,
                totalMarks: challengeQuestions.length,
                isAutoGenerated: true,
                status: 'published'
            });

            generatedCount++;
        }

        return NextResponse.json({ 
            success: true, 
            message: `Successfully generated ${generatedCount} challenges. Skipped ${skippedCount} existing dates.`,
            generated: generatedCount,
            skipped: skippedCount
        }, { status: 201 });

    } catch (error) {
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
