/**
 * robotsMeta.js
 * AdSense-safe robots meta controller for quiz pages.
 * - SSR-safe
 * - Conservative by default
 * - Bulk-update resistant (learningOutcomes alone never unlock indexing)
 */

const toBool = (v, def = false) => {
    if (typeof v === 'boolean') return v;
    if (typeof v === 'string') return v.toLowerCase() === 'true';
    return def;
};

const ENV = {
    enabled: toBool(process.env.QUIZ_NOINDEX_ENABLED ?? 'true'),
    threshold: parseFloat(process.env.QUIZ_CONTENT_SCORE_THRESHOLD ?? '0.5'),
    minIntroWords: parseInt(process.env.QUIZ_MIN_INTRO_WORDS ?? '300', 10),
    safeMode: toBool(process.env.QUIZ_SAFE_MODE ?? 'true'),
};

/**
 * Compute content quality score (0.0 – 1.0)
 * IMPORTANT:
 * - ONLY long-form editorial text counts as "intro"
 * - learningOutcomes / syllabus are SUPPORTING only
 */
function computeContentScore(quiz = {}, opts = {}) {
    const minIntroWords = opts.minIntroWords ?? ENV.minIntroWords;

    // 🔒 ONLY editorial intro text counts
    const introText = [
        quiz.description,
        quiz.educationalDescription,
    ]
        .filter(Boolean)
        .join('\n\n')
        .trim();

    const introWordCount = introText
        ? introText.split(/\s+/).filter(Boolean).length
        : 0;

    const hasStrongIntro = introWordCount >= minIntroWords;

    // Supporting content (never unlocks indexing alone)
    const hasLearningOutcomes =
        Array.isArray(quiz.learningOutcomes) && quiz.learningOutcomes.length > 0;

    const hasSummary = !!(
        (quiz.summary && quiz.summary.trim()) ||
        (quiz.conclusion && quiz.conclusion.trim()) ||
        (quiz.summaryText && quiz.summaryText.trim())
    );

    const autoGenerated = !!(
        quiz.autoGenerated ||
        quiz.isAutoGenerated ||
        quiz.generatedAutomatically ||
        quiz.flagAutoGenerated
    );

    // Scoring (conservative)
    let score = 0;

    if (hasStrongIntro) score += 0.6;              // mandatory gate
    if (hasStrongIntro && hasLearningOutcomes) score += 0.2;
    if (hasStrongIntro && hasSummary) score += 0.2;
    if (autoGenerated) score -= 0.6;

    score = Math.max(0, Math.min(1, score));

    return {
        score,
        details: {
            introWordCount,
            hasStrongIntro,
            hasLearningOutcomes,
            hasSummary,
            autoGenerated,
            minIntroWords,
        },
    };
}

/**
 * Decide robots meta for a quiz page
 */
function getRobotsMeta(quiz = {}, opts = {}) {
    const enabled = opts.enabled ?? ENV.enabled;
    const threshold = typeof opts.threshold === 'number' ? opts.threshold : ENV.threshold;
    const safeMode = opts.safeMode ?? ENV.safeMode;

    // Global off
    if (!enabled) {
        return { robots: 'index, follow', reason: 'disabled_via_env', scoreDetail: null };
    }

    // DB override wins
    if (quiz.noindexOverride === true) {
        return { robots: 'noindex, follow', reason: 'override_db_true', scoreDetail: null };
    }
    if (quiz.noindexOverride === false) {
        return { robots: 'index, follow', reason: 'override_db_false', scoreDetail: null };
    }

    const { score, details } = computeContentScore(quiz, opts);

    // 🚨 HARD GATE: no strong intro = NEVER index
    if (!details.hasStrongIntro) {
        return {
            robots: 'noindex, follow',
            reason: 'no_strong_intro',
            scoreDetail: details,
        };
    }

    // Score-based decision
    if (score < threshold) {
        if (safeMode) {
            return {
                robots: 'noindex, follow',
                reason: `low_score:${score.toFixed(2)}<${threshold}`,
                scoreDetail: details,
            };
        }
        return {
            robots: 'noindex, nofollow',
            reason: `low_score_aggressive:${score.toFixed(2)}<${threshold}`,
            scoreDetail: details,
        };
    }

    return {
        robots: 'index, follow',
        reason: `ok:${score.toFixed(2)}>=${threshold}`,
        scoreDetail: details,
    };
}

module.exports = {
    getRobotsMeta,
    computeContentScore,
    _ENV: ENV,
};
