// Paper 1 (17 Sep 2018) — corrected Q51-100. Scramble-pairs resolved.
// Dropped (lost/garbled/ambiguous): 53,56,57,58,59,61,62,64,66,67,68,69,70,71,72,76,80,81,82,83,86,91,93,95,96,98.
export const PART = [
  { orig:51, s:"General Science", a:3,
    q:"As long as an unbalanced force is applied to a body, there is a continuous change in its:",
    o:["weight","mass","speed","shape"] },
  { orig:52, s:"General Science", a:3,
    q:"Which of the following options is an example of a salt that gives an aqueous solution of pH less than 7?",
    o:["Sodium carbonate","Sodium chloride","Ammonium chloride","Sodium bicarbonate"] },
  { orig:54, s:"General Awareness & Current Affairs", a:2,
    q:"Which of the following is known as 'the Princess of Hill Stations'?",
    o:["Dehradun","Kodaikanal","Darjeeling","Ooty"] },
  { orig:55, s:"General Awareness & Current Affairs", a:2,
    q:"Identify the award which recognises workers for their distinguished performance, innovative ability, outstanding contribution in the field of productivity and exhibition of exceptional courage and presence of mind.",
    o:["Krishi Awards","Shram Awards","Padma Awards","Dronacharya Award"] },
  { orig:60, s:"General Awareness & Current Affairs", a:3,
    q:"Which of the following is known as the Upper House of the Indian Parliament?",
    o:["Supreme Court","PMO","Rajya Sabha","Lok Sabha"] },
  { orig:63, s:"General Awareness & Current Affairs", a:3,
    q:"What is 'Hausala 2017', which was celebrated from 16th November to 20th November 2017?",
    o:["Celebration of transgender rights","Celebration of women's rights","Celebration of children's rights","Celebration of senior citizen's rights"] },
  { orig:65, s:"General Science", a:3,
    q:"Which of the following can exist in solid, liquid and gaseous forms?",
    o:["Metalloids","Inert elements","Non-metals","Metals"] },
  { orig:73, s:"General Science", a:3,
    q:"The chemical symbol of which of the following elements is derived from Latin?",
    o:["Chlorine","Carbon","Iron","Aluminium"] },
  { orig:74, s:"Mathematics", a:4,
    q:"If a driver drives a car at 15 m/s, then how much distance is covered by him in 3 hours 20 mins?",
    o:["200 km","165 km","150 km","180 km"] },
  { orig:78, s:"General Intelligence & Reasoning", a:3,
    q:"It was Monday on 1st January 2018. What was the day of the week on 1st January 2010?",
    o:["Tuesday","Thursday","Friday","Monday"] },
  { orig:79, s:"Mathematics", a:1,
    q:"Achuth opens a tea shop with an initial investment of ₹25,000. He spends 30% of his money in furnishing his shop and 20% in bringing other necessary accessories. How much money is he left with for purchasing inventory for his business?",
    o:["₹12,500","₹20,000","₹12,000","₹5,000"] },
  { orig:84, s:"General Science", a:2,
    q:"Which of the following animals can produce ultrasound?",
    o:["Moths","Porpoises","Shark","Elephant"] },
  { orig:85, s:"Mathematics", a:2,
    q:"Anurag loses one-seventh of the cost by selling a pen for ₹144. If the pen is sold for ₹189, what is the gain percent?",
    o:["11%","12.5%","11.5%","14%"] },
  { orig:87, s:"General Intelligence & Reasoning", a:4,
    q:"Choose the person who does NOT belong to the group.",
    o:["Alexander Graham Bell","Albert Einstein","Thomas A. Edison","Virat Kohli"] },
  { orig:88, s:"General Awareness & Current Affairs", a:3,
    q:"Which of the following countries has the longest coastline in the world?",
    o:["Australia","Norway","Canada","Indonesia"] },
  { orig:89, s:"General Intelligence & Reasoning", a:3,
    q:"If South becomes South-West, then what will North become?",
    o:["South-West","North-West","North-East","South-East"] },
  { orig:90, s:"General Intelligence & Reasoning", a:3,
    q:"On what dates of March 2005 did Friday fall?",
    o:["5, 12, 19 and 26","3, 10, 17 and 24","4, 11, 18 and 25","6, 13, 20 and 27"] },
  { orig:92, s:"General Science", a:4,
    q:"The flexibility in plants is due to ____ tissue.",
    o:["xylem","phloem","sclerenchyma","collenchyma"] },
  { orig:94, s:"General Science", a:3,
    q:"Generally, the valency of electropositive elements is:",
    o:["2, 1, 0","4, 3, 2","1, 2, 3","0, 1, 2"] },
  { orig:97, s:"General Science", a:3,
    q:"A type of reproduction in which a part of a plant body develops into a new individual is called:",
    o:["fission","regeneration","vegetative propagation","sexual propagation"] },
  { orig:99, s:"Mathematics", a:1,
    q:"Two inlet pipes, A and B, can fill an empty cistern in 22 and 33 hours, respectively. They were opened at the same time, but pipe A had to be closed 3 hours before the cistern was full. How many hours in total did it take the two pipes to fill the cistern?",
    o:["15","16.2","14.2","16"] },
  { orig:100, s:"General Science", a:1,
    q:"What will be the direction of the magnetic field at a point directly below a horizontal power line with the current flowing from east to west when viewed from the west end?",
    o:["Anticlockwise","Clockwise","Parallel to the flow of the current","Perpendicular to the flow of the current"] },
];
