// Paper 1 (17 Sep 2018) — corrected Q1-50. Bilingual paper; Hindi/Marathi Qs translated.
// Dropped (lost/garbled/Marathi-garbled opts): 11,16,20,22,24,25,33,35,39,41,46,49.
export const PART = [
  { orig:1, s:"Mathematics", a:1,
    q:"₹720 was divided among A, B, C, D, E. The sum received by them was in ascending order and in Arithmetic Progression. E received ₹40 more than A. How much did B receive?",
    o:["₹134","₹154","₹144","₹124"] },
  { orig:2, s:"General Awareness & Current Affairs", a:2,
    q:"Who portrayed the character of Allauddin Khilji in the controversial movie 'Padmavat'?",
    o:["Shahid Kapoor","Ranveer Singh","Ranbir Kapoor","Rana Daggubati"] },
  { orig:3, s:"General Awareness & Current Affairs", a:2,
    q:"How many medals did India win in the US Open Karate Championship held in Las Vegas in April 2017?",
    o:["17","16","12","15"] },
  { orig:4, s:"General Awareness & Current Affairs", a:3,
    q:"Dayanand Saraswati was the founder of which of the following missions?",
    o:["Brahmo Samaj","Chinmaya Mission","Arya Samaj","Prarthana Samaj"] },
  { orig:5, s:"General Science", a:4,
    q:"The mass of the Earth is:",
    o:["6 × 10⁻²⁷ kg","6 × 10²³ kg","6 × 10⁻²⁴ kg","6 × 10²⁴ kg"] },
  { orig:6, s:"General Intelligence & Reasoning", a:1,
    q:"Find the next term in the following series.\n5I, 7J, 11L, 17O, ?",
    o:["25S","25Y","20P","18C"] },
  { orig:7, s:"General Intelligence & Reasoning", a:1,
    q:"Which of the given assumptions are implied from the below statement?\n\nStatement: \"I need your notes to study,\" said student 1 to student 2.\n\nAssumptions:\nI. Student 2 has prepared notes.\nII. Student 1 wants to verify his understanding.",
    o:["Only I is implicit","Both I and II are implicit","Neither I nor II is implicit","Only II is implicit"] },
  { orig:8, s:"Mathematics", a:4,
    q:"Two trains, one 152.5 m long and the other 157.5 m long, coming from opposite directions crossed each other in 9.3 seconds. The combined speed of the two trains every hour would then be:",
    o:["130 km","125 km","115 km","120 km"] },
  { orig:9, s:"General Science", a:2,
    q:"In the modern periodic table, which group elements have a complete outer shell?",
    o:["15th","18th","16th","17th"] },
  { orig:10, s:"General Intelligence & Reasoning", a:2,
    q:"What is the next term in this series?\nB25Y, D23W, F21U, ?",
    o:["I19V","H19S","I20T","H20V"] },
  { orig:12, s:"General Science", a:2,
    q:"The ratio of the mass of hydrogen to the mass of oxygen (in water) is always:",
    o:["2 : 1","1 : 8","8 : 1","1 : 2"] },
  { orig:13, s:"General Science", a:1,
    q:"Which of the following animals is warm-blooded?",
    o:["Pigeon","Fish","Crocodile","Toad"] },
  { orig:14, s:"General Awareness & Current Affairs", a:4,
    q:"Which of the following countries hosts the Academy (Oscar) Awards for excellence in cinema every year?",
    o:["France","UK","Canada","USA"] },
  { orig:15, s:"Mathematics", a:4,
    q:"Which of the following is a pair of twin prime numbers?",
    o:["(43, 47)","(3, 7)","(37, 41)","(71, 73)"] },
  { orig:17, s:"General Awareness & Current Affairs", a:3,
    q:"Which of the following sports is Satyawart Kadiyan related to?",
    o:["Hockey","Kabaddi","Wrestling","Football"] },
  { orig:18, s:"General Science", a:4,
    q:"Which of the following metals reacts with steam to form metal oxide and hydrogen?",
    o:["Copper","Silver","Lead","Aluminium"] },
  { orig:19, s:"Mathematics", a:3,
    q:"The area of the triangle whose vertices are given by (1, 2), (−4, −3) and (4, 1) is:",
    o:["7 sq. units","20 sq. units","10 sq. units","14 sq. units"] },
  { orig:21, s:"General Awareness & Current Affairs", a:2,
    q:"President Ram Nath Kovind felicitated exceptional women achievers ('First Ladies', those who are first to set a milestone of achievement in their respective fields) at Rashtrapati Bhawan in New Delhi. How many such 'First Ladies' were felicitated?",
    o:["111","112","114","113"] },
  { orig:23, s:"General Science", a:3,
    q:"The resistance of a conductor does NOT depend on which of the following factors?",
    o:["Length","Area of cross section","Pressure","Material"] },
  { orig:27, s:"General Awareness & Current Affairs", a:2,
    q:"What was the theme of the 2016 Indian Film Festival of Melbourne (IFFM) at which Sonam Kapoor won the Best Actress Award for her performance in Neerja Bhanot's biopic 'Neerja'?",
    o:["Enrichment of Women Status","Female Empowerment","Beti Bachao","Celebration of Life"] },
  { orig:28, s:"General Intelligence & Reasoning", a:4, img:"image140.jpeg",
    q:"How many triangles are there in the following figure?",
    o:["25","23","24","27"] },
  { orig:29, s:"General Awareness & Current Affairs", a:1,
    q:"Name the badminton player who won his maiden Super Series title in Singapore in April 2017.",
    o:["Sai Praneeth","Srikanth Kidambi","Prannoy Kumar","Parupalli Kashyap"] },
  { orig:30, s:"General Intelligence & Reasoning", a:1,
    q:"You are given a question and two statements. Identify which of the statements is/are necessary/sufficient to answer the question.\n\nWhat is the total weight of 20 cartons of vegetables? Each of them weighs equal.\n\nStatements:\n1. Of the first 10 boxes, one-third of each box weighs 10 kg.\n2. The total weight of 6 boxes is 40 kg more than the total weight of 4 boxes.",
    o:["Both Statements 1 and 2 alone are sufficient","Statement 2 alone is sufficient","Statement 1 alone is sufficient","Statement 1 and 2 are not sufficient"] },
  { orig:31, s:"General Science", a:1,
    q:"In which of the following processes is oxygen released into the air?",
    o:["Photosynthesis","Respiration","Transpiration","Excretion"] },
  { orig:32, s:"General Science", a:4,
    q:"In which of the following media does sound travel the fastest?",
    o:["Gases","Vacuum","Liquids","Solids"] },
  { orig:34, s:"General Science", a:2,
    q:"In physics, work done is defined as:\nA. A force has acted on an object without causing any displacement of it.\nB. Object is displaced.\nC. A force has acted on the object.\nD. All of the above.",
    o:["D is correct","B and C are correct","A and B are correct","A and C are correct"] },
  { orig:36, s:"General Awareness & Current Affairs", a:4,
    q:"A committee under the chairmanship of Uday Kotak was constituted in 2017 to improve efficiency in:",
    o:["customer satisfaction","labour management relations","government policies","corporate governance"] },
  { orig:37, s:"General Science", a:4,
    q:"The fertilised egg, the zygote, gets implanted in the:",
    o:["cervix","ovary","vagina","uterus"] },
  { orig:38, s:"General Science", a:3,
    q:"When a body moves on a circular path, the force that acts on the revolving body towards the centre is called:",
    o:["simple force","gravitational force","centripetal force","angular force"] },
  { orig:40, s:"General Awareness & Current Affairs", a:2,
    q:"Name the first city in India to use a robot to control traffic.",
    o:["Kochi","Indore","Varanasi","Jaipur"] },
  { orig:42, s:"General Awareness & Current Affairs", a:3,
    q:"Which is the second company to hit $900 billion market capitalization after Apple?",
    o:["Google","Walmart","Amazon","Facebook"] },
  { orig:43, s:"General Awareness & Current Affairs", a:1,
    q:"Which union minister has launched the PowerTex India scheme to boost the powerloom sector?",
    o:["Smriti Irani","Maneka Gandhi","Nitin Gadkari","Ravi Shankar Prasad"] },
  { orig:44, s:"General Awareness & Current Affairs", a:2,
    q:"Which of the following state governments launched the 'Quit India 2 - from Swaraaj to Suraaj' initiative at the historic August Kranti Maidan in August 2016?",
    o:["Haryana","Maharashtra","Madhya Pradesh","West Bengal"] },
  { orig:45, s:"General Awareness & Current Affairs", a:1,
    q:"Who has been chosen for the RedInk Award for Lifetime Achievement in Journalism for 2018?",
    o:["Mark Tully","Arun Shourie","Barkha Dutt","N. Ram"] },
  { orig:47, s:"Mathematics", a:4,
    q:"Rohan and Rohit together can do a certain job in 10 days while Rohan alone can do the same job in 15 days. In how many days will Rohit alone do the same job?",
    o:["25 days","32 days","35 days","30 days"] },
  { orig:48, s:"Mathematics", a:2,
    q:"The compound interest on ₹1,60,000 for 2 years at 10% per annum when compounded semi-annually is:",
    o:["₹34,400","₹34,481","₹30,000","₹34,480"] },
  { orig:50, s:"General Science", a:3,
    q:"A force increases the speed of a 1.0 kg object from 4 m/s to 8 m/s. The work done by the force will be:",
    o:["8 J","32 J","24 J","16 J"] },
];
