// Paper 2 (18 Sep 2018) — corrected Q73-100. Dropped: 76,90,95,99.
// Q84 graph values embedded. Q85 pie chart -> image-seed.
export const PART = [
  { orig:73, s:"General Intelligence & Reasoning", a:4,
    q:"Mamata is the mother of Surya. How is Mamata's brother related to Surya's brother?",
    o:["Grandfather","Father","Brother","Maternal uncle"] },
  { orig:74, s:"General Awareness & Current Affairs", a:1,
    q:"The name of the comprehensive mentorship programme tailored exclusively for Indian startups that are using Machine Learning (ML) and Artificial Intelligence (AI) to build solutions for the pressing problems in the country is:",
    o:["Launchpad Accelerator India","Modernization Accelerator India","Automation Accelerator India","MLAI Accelerator India"] },
  { orig:75, s:"General Science", a:3,
    q:"A ray of light passes from water to glass. It bends:",
    o:["away from the normal and speeds up","away from the normal and slows down","towards the normal and slows down","towards the normal and speeds up"] },
  { orig:77, s:"General Science", a:3,
    q:"A 40 kg girl runs up a flight of stairs having a rise of 5 m in 4 s. The power developed by her will be ____. (take g = 10 m/s²)",
    o:["100 W","200 W","500 W","2000 W"] },
  { orig:78, s:"Mathematics", a:2,
    q:"If ₹686 is divided into four parts, in proportions ½ : ⅔ : 3 : 4, then the first part is?",
    o:["₹52","₹42","₹56","₹48"] },
  { orig:79, s:"General Awareness & Current Affairs", a:2,
    q:"The Election Commission of India (ECI) celebrated 8th National Voters' Day across the nation on ____ for enhanced participation of citizens in the electoral process.",
    o:["28th January","25th January","24th January","26th January"] },
  { orig:80, s:"General Awareness & Current Affairs", a:2,
    q:"Which is the longest river of Europe?",
    o:["Danube","Volga","Ural","Rhine"] },
  { orig:81, s:"Mathematics", a:1,
    q:"Find the compound interest on ₹50000 at 12% per annum for 6 months, compounded quarterly.",
    o:["₹3045","₹2875","₹3125","₹2965"] },
  { orig:82, s:"General Awareness & Current Affairs", a:2,
    q:"The Ministry of Women and Child Development had launched a social media campaign to mark ____ on 11 August 2016.",
    o:["Women's Day","Daughter's Day","Son's Day","Men's Day"] },
  { orig:83, s:"General Science", a:4,
    q:"The induced current is highest when the direction of motion of the coil is at ____ with respect to the magnetic field.",
    o:["0°","45°","180°","90°"] },
  { orig:84, s:"Mathematics", a:1,
    q:"Study the following data carefully and answer the question.\n\nTotal Area of Tea Cultivation of three states — Tamil Nadu: 16%, West Bengal: 22%, Assam: 62%.\n\nArea cultivated in West Bengal is what percentage more than that cultivated in Tamil Nadu?",
    o:["6%","8%","4%","3%"] },
  { orig:85, s:"Mathematics", a:2, img:"image396.jpeg",
    q:"The given pie chart shows information about the mobile phone manufacturing companies in India. The total number of mobile phone units manufactured is 12,40,000.\n\nHow many units of mobile phones are manufactured by company 'DEF'?",
    o:["1,24,000","62,000","31,000","15,600"] },
  { orig:86, s:"General Science", a:4,
    q:"The breakdown of pyruvate using O₂ takes place in the ____.",
    o:["lysosomes","nucleus","vacuoles","mitochondria"] },
  { orig:87, s:"General Awareness & Current Affairs", a:4,
    q:"Which of the following nations is the only country to win the ICC Under-19 Cricket World Cup four times?",
    o:["New Zealand","South Africa","Australia","India"] },
  { orig:88, s:"Mathematics", a:2,
    q:"Which of the following numbers will have an irrational square root?",
    o:["11025","6025","9025","3025"] },
  { orig:89, s:"General Awareness & Current Affairs", a:4,
    q:"Who was awarded the 2017 Sahitya Akademi award for his English novel 'The Black Hill'?",
    o:["Vikram Seth","Chetan Bhagat","Amitav Ghosh","Mamang Dai"] },
  { orig:91, s:"Mathematics", a:4,
    q:"The lengths of one side of a rhombus and one of the two diagonals are 6 cm each. The area of the rhombus (in cm²) is:",
    o:["27√3","18","9√3","18√3"] },
  { orig:92, s:"Mathematics", a:1,
    q:"The ratio 75 : 125 in its simplest form is written as:",
    o:["3 : 5","5 : 3","2 : 3","3 : 2"] },
  { orig:93, s:"General Science", a:4,
    q:"Which of the following is malleable and ductile?",
    o:["Phosphorus","Sulphur","Carbon","Copper"] },
  { orig:94, s:"General Science", a:2,
    q:"Sound waves with frequencies below the audible range are called:",
    o:["ultrasonic","infrasonic","supersonic","ultrasound"] },
  { orig:96, s:"General Science", a:4,
    q:"A ball is dropped from a height of 80 m. The distance travelled by it in the fourth second will be ____. (take g = 10 m/s²)",
    o:["50 m","15 m","80 m","35 m"] },
  { orig:97, s:"General Science", a:2,
    q:"5-8% of acetic acid is called:",
    o:["glacial acetic acid","vinegar","ester","ethanol"] },
  { orig:98, s:"Mathematics", a:2,
    q:"If P is 15 years now and Q will be 26 years old after 6 years, what is the ratio of their present ages?",
    o:["4 : 1","3 : 4","2 : 1","2 : 3"] },
  { orig:100, s:"General Intelligence & Reasoning", a:2,
    q:"Find the day name of 24 March 2006?",
    o:["Monday","Friday","Wednesday","Sunday"] },
];
