// Paper 2 (18 Sep 2018) — corrected Q49-72. Dropped: 52,62,63,65,69.
// Q49,Q51,Q60 translated from Hindi. Q68 figure -> image-seed (img field).
export const PART = [
  { orig:49, s:"General Science", a:4,
    q:"Which of the following animals reproduces by budding and can also carry out regeneration?",
    o:["Plasmodium","Yeast","Planaria","Hydra"] },
  { orig:50, s:"General Intelligence & Reasoning", a:2,
    q:"If North-East becomes North, then what will East become?",
    o:["South-East","North-East","North-West","South-West"] },
  { orig:51, s:"General Awareness & Current Affairs", a:4,
    q:"Karewa, which is a type of soil/silt, is found in which Indian state?",
    o:["Rajasthan","West Bengal","Nagaland","Jammu & Kashmir"] },
  { orig:53, s:"General Science", a:3,
    q:"Electric bulbs are usually filled with chemically-inactive gases like ____.",
    o:["hydrogen","oxygen","nitrogen","chlorine"] },
  { orig:54, s:"Mathematics", a:4,
    q:"If the length and breadth of a rectangle are increased by 8% and 12% respectively, then by what percent does the area of that rectangle increase?",
    o:["22%","24%","20%","20.96%"] },
  { orig:55, s:"General Science", a:4,
    q:"Who classified elements based on atomic numbers?",
    o:["Newlands","Mendeleev","Dobereiner","Moseley"] },
  { orig:56, s:"General Awareness & Current Affairs", a:1,
    q:"Who has been crowned Femina Miss India 2018?",
    o:["Anukreethy Vas","Shreya Rao Kamavarapu","Sunaina Kamath","Meenakshi Chaudhary"] },
  { orig:57, s:"General Science", a:2,
    q:"A chemical reaction in which heat is generated is called a/an ____.",
    o:["endothermic reaction","exothermic reaction","combustion reaction","displacement reaction"] },
  { orig:58, s:"General Awareness & Current Affairs", a:4,
    q:"Which of the following sport is Yuzvendra Chahal related to?",
    o:["Tennis","Hockey","Shooting","Cricket"] },
  { orig:59, s:"General Awareness & Current Affairs", a:3,
    q:"Who won the Filmfare Best Actor in a Leading Role (Male) award 2017?",
    o:["Shahrukh Khan","Ranveer Singh","Aamir Khan","Ranbir Kapoor"] },
  { orig:60, s:"General Intelligence & Reasoning", a:4,
    q:"Which one of the following does NOT belong to the group?",
    o:["Nail","Hair","Pimples","Toe"] },
  { orig:61, s:"General Intelligence & Reasoning", a:4,
    q:"Find the next number in the following series.\n16, 18, 22, 24, 28, 30, ?",
    o:["25","30","27","34"] },
  { orig:64, s:"General Science", a:3,
    q:"The point where the entire weight of an object acts is known as the ____.",
    o:["centre of friction","centre of mass","centre of gravity","centre of pressure"] },
  { orig:66, s:"Mathematics", a:3,
    q:"If '+' means '÷', '÷' means '−', '−' means '×' and '×' means '+', then what is the value of 80 + 20 ÷ 5 − 12 × 92?",
    o:["28","22","36","35"] },
  { orig:67, s:"General Science", a:2,
    q:"The weight of an object on the moon is how many times its weight on the earth?",
    o:["1/5 times","1/6 times","5 times","6 times"] },
  { orig:68, s:"Mathematics", a:2, img:"image318.jpeg",
    q:"Find the number of squares in the following figure.",
    o:["22","21","23","20"] },
  { orig:70, s:"General Science", a:3,
    q:"The correct formula of calcium hydroxide is:",
    o:["CaOH₂","Ca₂OH","Ca(OH)₂","CaOH"] },
  { orig:71, s:"General Awareness & Current Affairs", a:3,
    q:"Name the book authored by K. R. Meera which raises pertinent questions about the politics of faithfulness and the price of idealism.",
    o:["Gilletin","Nethromeelanam","The Gospel of Yudas","Aarachar"] },
  { orig:72, s:"Mathematics", a:4,
    q:"In a class there were 9 boys and some girls. In a test, the mean score obtained by the boys was 13 while that obtained by the girls was 15. If the overall average was 14.28, what was the total number of students in the class?",
    o:["24","26","27","25"] },
];
