// Paper 2 (18 Sep 2018) — corrected Q25-48. Dropped: 30,32,40,41,42,47,48.
// Q33,Q36 translated from Hindi source. Q37 answer resolved (no key in source).
export const PART = [
  { orig:25, s:"General Intelligence & Reasoning", a:1,
    q:"Consider the given statement and decide which of the following assumptions is/are implicit in the statement.\n\nStatement: \"The final exams are getting near\", Rina reminded her daughters.\n\nAssumptions:\nI. She wants them to remember about their study schedule.\nII. She wants them to give serious thought to their exams.",
    o:["Both I and II are implicit.","Only II is implicit.","Neither I nor II is implicit.","Only I is implicit."] },
  { orig:26, s:"General Awareness & Current Affairs", a:2,
    q:"The Central Government's initiative aimed at bringing masses within the formal banking system is called:",
    o:["Jan Bank Yojana","Jan Dhan Yojana","Jan Aadmi Yojana","Jan Rupaya Yojana"] },
  { orig:27, s:"General Awareness & Current Affairs", a:4,
    q:"In March 2018, who released ₹1,000 and ₹10 commemorative coins on the occasion of the Nabakalebara festival at a function held in Puri, Odisha?",
    o:["The Governor of Odisha","The Chief Minister of Odisha","The Prime Minister of India","The President of India"] },
  { orig:28, s:"Mathematics", a:1,
    q:"4 + 4.44 + 44.4 + 4.04 + 444 − 20 = ?",
    o:["480.88","472.88","495.22","577.2"] },
  { orig:29, s:"General Science", a:4,
    q:"In which group of the modern periodic table are halogens placed?",
    o:["16th","18th","1st","17th"] },
  { orig:31, s:"Mathematics", a:2,
    q:"A car covers a distance of 44 km using 2¾ litres of petrol. What distance can the car cover using 1 litre of petrol?",
    o:["14 km","16 km","13 km","15 km"] },
  { orig:33, s:"General Science", a:3,
    q:"Which of the following hormones brings about the changes that appear in boys at the time of puberty?",
    o:["Animal hormone","Thyroxine","Testosterone","Insulin"] },
  { orig:34, s:"General Awareness & Current Affairs", a:1,
    q:"Which of the following states emerged as overall champions of the first (inaugural) edition of Khelo India School Games (KISG) held from 31st January to 8th February 2018 at Indira Gandhi Indoor Stadium?",
    o:["Haryana","Gujarat","Maharashtra","Uttar Pradesh"] },
  { orig:35, s:"General Awareness & Current Affairs", a:4,
    q:"From which Indian princely state did Velu Thampi Dalava hail? He is known for revolting against the British.",
    o:["Chola Kingdom","Mysore Kingdom","Vijayanagaram","Travancore"] },
  { orig:36, s:"General Intelligence & Reasoning", a:4,
    q:"Select the option that is related to the third word in the same way as the second word is related to the first word.\n\nGlass : Transparent :: Wood : ____",
    o:["Furniture","Belly","Block","Opaque"] },
  { orig:37, s:"General Science", a:3,
    q:"If two unequal masses possess the same kinetic energy, then the heavier mass has:",
    o:["higher speed","lesser momentum","greater momentum","lower speed"] },
  { orig:38, s:"Mathematics", a:2,
    q:"If 15 boys earn ₹750 in 5 days, then how much money will 25 boys earn in 6 days?",
    o:["960","1500","1200","900"] },
  { orig:39, s:"General Science", a:4,
    q:"Which of the following compounds does NOT possess water of crystallisation?",
    o:["Gypsum","Washing soda","Copper sulphate","Baking soda"] },
  { orig:43, s:"General Intelligence & Reasoning", a:4,
    q:"If South becomes South-East, then what will North become?",
    o:["South-West","North-East","South-East","North-West"] },
  { orig:44, s:"Mathematics", a:2,
    q:"Lata makes 20 kg paneer at home and sells it every morning. From one litre of milk, she makes 200 gms of paneer. The cost of a litre of milk is ₹40. How much money does she spend in procuring milk every day?",
    o:["₹3,000","₹4,000","₹2,000","₹2,500"] },
  { orig:45, s:"Mathematics", a:1,
    q:"If α and β are roots of the equation x² − x − 1 = 0, then the equation whose roots are α/β and β/α is:",
    o:["x² + 3x − 1 = 0","x² + x − 1 = 0","x² − x + 1 = 0","x² + 3x + 1 = 0"] },
  { orig:46, s:"Mathematics", a:3,
    q:"If a + b + c = 2s, then [(s−a)² + (s−b)² + (s−c)² + s²] = ?",
    o:["(s² − a² − b² − c²)","(s² + a² + b² + c²)","(a² + b² + c²)","(4s² − a² − b² − c²)"] },
];
