// Paper 2 (18 Sep 2018) — corrected Q1-24. Only kept questions. a=answer(1-4).
// Dropped (lost option/stem/figure): 1,4,6,9,13,14,15.
export const PART = [
  { orig:2,  s:"General Science", a:3,
    q:"An electric lamp of 120 W is used for 8 hours per day. Calculate the units of energy consumed by the lamp in one day.",
    o:["16.00 unit","1.50 unit","0.96 unit","2.00 unit"] },
  { orig:3,  s:"General Awareness & Current Affairs", a:2,
    q:"In which year was the Battle of Waterloo fought?",
    o:["1835","1815","1850","1840"] },
  { orig:5,  s:"General Science", a:2,
    q:"Two resistors, one of 10 Ω and the other of 20 Ω, are connected in series to a 6 V battery. The current in the circuit will be:",
    o:["0.3 A","0.2 A","0.9 A","0.6 A"] },
  { orig:7,  s:"Mathematics", a:1,
    q:"In what time can Saloni cover a distance of 450 m, if she runs at a speed of 20 Km/hr?",
    o:["81 sec","320 sec","3 minutes","102 sec"] },
  { orig:8,  s:"Mathematics", a:1,
    q:"A merchant incurred a loss of 5% by selling a book for ₹25.65. If he sells it for ₹31.05, find his gain percent or loss percent.",
    o:["Gain 15%","Loss 15%","Gain 10%","Loss 10%"] },
  { orig:10, s:"General Awareness & Current Affairs", a:4,
    q:"Which of the following events is celebrated every year on January 9 to mark the contribution of the overseas Indian community in the development of India?",
    o:["Unnatiya Bharat Divas (UBD)","Overseas Indian Development Day (OIDD)","Akhil Bharatiya Divas (ABD)","Pravasi Bharatiya Divas (PBD)"] },
  { orig:11, s:"Mathematics", a:2,
    q:"When the following decimals are arranged in ascending order then what decimal number should be in the middle? 5.74, 6.03, 0.8, 0.658 and 7.2",
    o:["6.03","5.74","7.2","0.8"] },
  { orig:12, s:"General Intelligence & Reasoning", a:4,
    q:"If in a coded language, COCK is written as DPDL, then how will HEN be written in that language?",
    o:["HEO","IDP","ICO","IFO"] },
  { orig:16, s:"General Awareness & Current Affairs", a:3,
    q:"The 2018 best tableau award in the Republic Day parade was given away by Union Defence Minister Nirmala Sitharaman to the state of:",
    o:["Karnataka","Goa","Maharashtra","Gujarat"] },
  { orig:17, s:"General Science", a:3,
    q:"Which one of the following is NOT a simple permanent tissue?",
    o:["Sclerenchyma","Parenchyma","Xylem","Collenchyma"] },
  { orig:18, s:"Mathematics", a:2,
    q:"sin² 60° + cos² 30° + cot² 45° + sec² 60° = ?",
    o:["15/2","13/2","7/2","5/2"] },
  { orig:19, s:"General Intelligence & Reasoning", a:1,
    q:"Read the given question and decide which of the following equations is/are sufficient to answer the question.\n\nQuestion: What is the value of x?\nEquations:\n1) x² − 18x + 81 = 0\n2) p + q + r = 0",
    o:["Only 1 is sufficient.","Either 1 or 2 is sufficient.","Neither 1 nor 2 is sufficient.","Only 2 is sufficient."] },
  { orig:20, s:"General Science", a:3,
    q:"The pH of the solutions are given. Which of the solutions has the highest concentration of hydrogen ions?",
    o:["10.1","4.7","2.4","8.0"] },
  { orig:21, s:"Mathematics", a:1,
    q:"A train crossed a 110 m long platform in 13.5 seconds and a 205 m long platform in 18.25 seconds. What was the speed of the train?",
    o:["72 km/h","66 km/h","69 km/h","75 km/h"] },
  { orig:22, s:"Mathematics", a:2,
    q:"A cistern can be filled by two pipes A and B in 4 hours and 6 hours respectively. When full, the tank can be emptied by a third pipe C in 8 hours. If all taps are turned on at the same time, the cistern will be full in:",
    o:["40/7 hours","24/7 hours","16/7 hours","31/7 hours"] },
  { orig:23, s:"General Intelligence & Reasoning", a:2,
    q:"Aadhya walks 500 m towards North and then turns left and walks 250 m. In which direction is she with respect to her initial position?",
    o:["South-East","North-West","North-East","South-West"] },
  { orig:24, s:"General Science", a:4,
    q:"In which of the following plants is the plant body NOT differentiated into roots, stem and leaves?",
    o:["Riccia","Chara","Marsilea","Spirogyra"] },
];
