// Paper (19 Sep 2018, Shift-1) — English paper. Image-based answer-key source.
// Answers from reliable green-tick decode. Kept 68/100 text questions.
// Dropped (lost stem / blank-image options / pure-visual figure opts):
//   1,6,9,11,14,16,20,21,22,24,27,29,38,39,46,54,58,59,61,62,65,69,74,75,78,83,87,89,90,95,96,98.
// Several stems recovered from the "next-Q stem leaks into prev opt4" scramble (7,12,25,42,55,85,92,100).
const MATH = 'Mathematics';
const REA  = 'General Intelligence & Reasoning';
const SCI  = 'General Science';
const GA   = 'General Awareness & Current Affairs';

export const PART = [
  { orig:2, s:GA, a:4,
    q:"Which party won the highest number of seats in the Manipur Legislative Assembly Elections held in 2017?",
    o:["Lok Jan Shakti Party","Bharatiya Janata Party","Aam Aadmi Party","Indian National Congress"] },
  { orig:3, s:REA, a:1,
    q:"Select the term that is related to the third term in the same way that the second term relates to the first term.\nWrist : Watch :: Finger : ?",
    o:["Ring","Joint","Nail","Thumb"] },
  { orig:4, s:REA, a:3,
    q:"Find the next term in the following series.\n33, 38, 48, 53, ?",
    o:["58","54","63","60"] },
  { orig:5, s:MATH, a:3,
    q:"The height and the slant height of a right circular cone are given as 3√23 cm and 16 cm respectively. Approximating π by 22/7, find the curved surface area of the said cone.",
    o:["328 cm²","339 cm²","352 cm²","372 cm²"] },
  { orig:7, s:SCI, a:2,
    q:"Name the process in which a metal is attacked by substances around it such as moisture, acids, etc.",
    o:["Oxidation","Corrosion","Rancidity","Reduction"] },
  { orig:8, s:GA, a:1,
    q:"In December 2017, who was conferred with the National Design Award?",
    o:["G. Satheesh Reddy","G. Shanthi Reddy","G. Ganesh Reddy","G. Shankar Reddy"] },
  { orig:10, s:GA, a:3,
    q:"The Jallianwala Bagh Massacre event took place in the year ______.",
    o:["1920","1981","1919","1891"] },
  { orig:12, s:GA, a:2,
    q:"On 19th January 2018, who was appointed as the Chief Election Commissioner of India?",
    o:["Ashok Lavasa","Om Prakash Rawat","Sunil Arora","Sunil Rawar"] },
  { orig:13, s:REA, a:1,
    q:"Consider the following question and statements and decide which of the statements is sufficient to answer the question.\n\nWhat is the total weight of six boxes? Each of them is equal in weight.\n\nStatements:\n1. One-third of each box's weight is 2 kg.\n2. The total weight of four boxes is 12 kg more than the total weight of two boxes.",
    o:["Either statement 1 or 2 is sufficient","Statement 1 alone is sufficient","Statement 2 alone is sufficient","Neither statement 1 nor 2 are sufficient"] },
  { orig:15, s:SCI, a:4,
    q:"How many atoms are present in one mole of copper?",
    o:["6.022 × 10²⁴","6.022 × 10²⁵","6.022 × 10²²","6.022 × 10²³"] },
  { orig:17, s:SCI, a:1,
    q:"Who coined the word 'atom'?",
    o:["Democritus","Thomson","E. Rutherford","John Dalton"] },
  { orig:18, s:REA, a:3,
    q:"Nina starts cycling early in the morning in the opposite direction to the sun. She then turns left, travels for 1 km and again turns left. Towards which direction is she moving?",
    o:["North","West","East","South"] },
  { orig:19, s:SCI, a:1,
    q:"The substances whose odour changes in acidic or basic media are called:",
    o:["olfactory indicators","synthetic indicators","acid-base indicators","natural indicators"] },
  { orig:23, s:REA, a:3,
    q:"In a certain code, TEAM is written as WHDP. How will COINS be written as in that code?",
    o:["QIPTU","FRLBZ","FRLQV","RVJQL"] },
  { orig:25, s:SCI, a:1,
    q:"Which of the following does NOT oxidise (burn) readily at high temperatures?",
    o:["Alloys","Insulators","Conductors","Semi-conductors"] },
  { orig:26, s:MATH, a:2,
    q:"The LCM of 14, 42 and 77 is:",
    o:["154","462","168","308"] },
  { orig:28, s:GA, a:4,
    q:"The South Asian Sports Council (SASC) was formed in the year ______.",
    o:["1975","1987","1979","1983"] },
  { orig:30, s:MATH, a:1,
    q:"After spending 85% of his salary, Alok saves ₹1200 per month. What is his monthly salary?",
    o:["₹8,000","₹10,000","₹8,500","₹12,000"] },
  { orig:31, s:GA, a:1,
    q:"Who was the first British Viceroy of India?",
    o:["Lord Canning","Lord Wellesley","William Bentinck","Robert Clive"] },
  { orig:32, s:MATH, a:4,
    q:"What is the difference between the compound interest and the simple interest on a sum of ₹4500 for 3 years at the rate of 8% per annum?",
    o:["₹87.70","₹87.50","₹85.70","₹88.70"] },
  { orig:33, s:MATH, a:2,
    q:"A triangle with vertices (4, 1), (1, 1), (3, 5) is a/an:",
    o:["Isosceles and right-angled triangle","Scalene triangle","Isosceles but not right-angled triangle","Right-angled but not isosceles triangle"] },
  { orig:34, s:REA, a:1,
    q:"On 7th June 1984 it was a Thursday. What day was it on 7th June 1983?",
    o:["Tuesday","Sunday","Wednesday","Monday"] },
  { orig:35, s:GA, a:3,
    q:"Apple introduced iPad as a multimedia device in the year ______.",
    o:["2008","2009","2010","2011"] },
  { orig:36, s:SCI, a:1,
    q:"The product of force and displacement is called ______.",
    o:["work","weight","acceleration","momentum"] },
  { orig:37, s:SCI, a:4,
    q:"Which of the below is not a part of 5-Kingdom classification by Whittaker?",
    o:["Animalia","Protista","Fungi","Protozoa"] },
  { orig:40, s:GA, a:3,
    q:"The first 'Persons of Indian Origin (PIO) Parliamentarian Conference' was held in ______.",
    o:["2 April 2017","19 January 2016","9 January 2018","11 July 2014"] },
  { orig:41, s:MATH, a:3,
    q:"Himanshi bought a t-shirt at 20% discount on its marked price but sold it at the marked price. What is the gain or loss percent on the whole transaction?",
    o:["15% gain","15% loss","25% gain","25% loss"] },
  { orig:42, s:SCI, a:1,
    q:"An object is placed in front of a concave mirror at a point between its focus and centre of curvature. The image formed will be ______.",
    o:["real and inverted","real and erect","virtual and inverted","virtual and erect"] },
  { orig:43, s:SCI, a:4,
    q:"A 10-kg object is moving at a speed of 5 m/s. The kinetic energy of the object will be ______.",
    o:["2 J","25 J","50 J","125 J"] },
  { orig:44, s:SCI, a:4,
    q:"Which of the following is NOT a simple permanent tissue?",
    o:["Apical meristem","Collenchyma","Cambium","Xylem"] },
  { orig:45, s:GA, a:2,
    q:"Viacom18 Media Pvt. Ltd. launched its Hindi movie channel Rishtey Cineplex in ______.",
    o:["March 2017","May 2016","October 2015","April 2014"] },
  { orig:47, s:GA, a:2,
    q:"What was the real name of the Indian director 'Guru Dutt'?",
    o:["Vasant Padukone","Vasant Kumar Shivashankar Padukone","Prabhakar Padukone","Shambhunath Padukone"] },
  { orig:48, s:REA, a:4,
    q:"Consider the following statement and conclusions and decide which of the conclusions logically follows from the statement.\n\nStatement: Of all the mobile brands, Samsung's sales are the highest.\n\nConclusions:\nI. The market share of other mobile brands is known.\nII. No other mobile brand is popular.",
    o:["Both the conclusions follow","Conclusion II alone follows","Neither conclusion I nor II follows","Conclusion I alone follows"] },
  { orig:49, s:SCI, a:4,
    q:"The melting point of tungsten is ______.",
    o:["3,830 °C","3,308 °C","3,083 °C","3,380 °C"] },
  { orig:50, s:SCI, a:4,
    q:"A free fall in true sense occurs only ______.",
    o:["in the sea","in the atmosphere","in air","in vacuum"] },
  { orig:51, s:SCI, a:2,
    q:"Which of the following is NOT required for photosynthesis?",
    o:["Sunlight","Oxygen","Carbon dioxide","Chlorophyll"] },
  { orig:52, s:MATH, a:1,
    q:"Without any stoppage Sunil travels a certain distance at an average speed of 80 km/hr. With stoppages, he covers the same distance at an average speed of 60 km/hr. How many minutes per hour does he stop?",
    o:["15 minutes","25 minutes","10 minutes","20 minutes"] },
  { orig:53, s:MATH, a:4,
    q:"If a workforce of 200 men can construct a building in 1024 days, how many men will be needed to construct the same building in 256 days?",
    o:["1400","650","1200","800"] },
  { orig:55, s:GA, a:1,
    q:"Who among the following was honoured with the Cecil B. DeMille Award at the 75th Golden Globe Awards?",
    o:["Oprah Winfrey","Audrey Hepburn","Goldie Hawn","Mother Teresa"] },
  { orig:56, s:MATH, a:2,
    q:"A tube can fill a tank in 15 hours. Due to a leak in the bottom, it is filled in 20 hours. If the tank is full, how much time will the leak alone take to empty it?",
    o:["20 hrs","60 hrs","32 hrs","40 hrs"] },
  { orig:57, s:MATH, a:3,
    q:"If 10sin⁴α + 15cos⁴α = 6, then find the value of 27cosec⁶α + 8sec⁶α.",
    o:["5","125","250","50"] },
  { orig:60, s:GA, a:1,
    q:"India is the largest producer, consumer, importer of ______.",
    o:["Pulses","Jute","Sugar","Salt"] },
  { orig:63, s:SCI, a:2,
    q:"Which of the following element could NOT find a fixed place in Mendeleev's periodic table?",
    o:["Sulphur","Hydrogen","Nitrogen","Oxygen"] },
  { orig:64, s:REA, a:3,
    q:"Find the next term in the following series.\n3B, 9F, 27J, ?",
    o:["80L","81L","81N","80N"] },
  { orig:66, s:GA, a:3,
    q:"To which country does the personality Aung San Suu Kyi belong? She is often seen in the news.",
    o:["Iran","Bhutan","Myanmar","Bangladesh"] },
  { orig:67, s:GA, a:2,
    q:"The headquarters of World Bank is located in which country?",
    o:["England","USA","Japan","Russia"] },
  { orig:68, s:REA, a:4,
    q:"Which of the following arguments is strong with relation to the given question?\n\nShould the government ban use of polythene bags in local vegetable markets?\n\nArguments:\nI. Yes, they pose a high risk to the environment. People can bring along their own bags to buy vegetables.\nII. No, it is convenient.",
    o:["Neither argument I nor II is strong","Both arguments I and II are strong","Only argument II is strong","Only argument I is strong"] },
  { orig:70, s:SCI, a:2,
    q:"Mechanical energy is:",
    o:["Equal to the rate of doing work","The sum of kinetic energy and the potential energy of an object","The energy released during mechanical work","The energy absorbed during movement of a body"] },
  { orig:71, s:REA, a:2,
    q:"C is the mother of E and F. F is married to Z. How is C related to Z?",
    o:["Mother","Mother-in-law","Daughter-in-law","Son-in-law"] },
  { orig:72, s:SCI, a:2,
    q:"A 1-kg object falls from a height of 30 m to the ground. The work done by the force of gravity will be ______. (Take g = 10 m/s²)",
    o:["10 J","300 J","30 J","0.33 J"] },
  { orig:73, s:REA, a:3,
    q:"If 'MAT' is coded as KYR in a certain language, how would 'HIS' be written in that language?",
    o:["FGT","FGR","FGQ","FGH"] },
  { orig:76, s:SCI, a:2,
    q:"Newlands' law of octaves was applicable only up to ______.",
    o:["potassium","calcium","chlorine","sulphur"] },
  { orig:77, s:GA, a:1,
    q:"Which of the following is the youngest mountain of India?",
    o:["Himalayas","Mount Abu","Satpura","Anamudi"] },
  { orig:79, s:SCI, a:3,
    q:"When two germ cells from two individuals combine during sexual reproduction, they form a ______.",
    o:["bud","spore","zygote","fruit"] },
  { orig:80, s:MATH, a:3,
    q:"Two men Kuldeep and Agarkar working separately can mow a field in 8 and 12 hrs respectively. If they work in stretches of one hour alternately, with Kuldeep beginning at 9 a.m., when will the mowing be finished?",
    o:["7.30 p.m.","5.30 p.m.","6.30 p.m.","4.30 p.m."] },
  { orig:81, s:SCI, a:4,
    q:"Which of the following metals is a liquid at room temperature?",
    o:["Tungsten","Bromine","Lead","Mercury"] },
  { orig:82, s:GA, a:3,
    q:"Who is the present CEO of ICICI bank?",
    o:["Arundhati Bhattacharya","Indra Nooyi","Chanda Kochhar","K. V. Kamat"] },
  { orig:84, s:GA, a:3,
    q:"The Income Declaration Scheme was launched by the Income Tax Department of the Government of India in the year ______.",
    o:["2015","2014","2016","2013"] },
  { orig:85, s:GA, a:4,
    q:"According to the Constitution of India, which House of Parliament passes the Constitution Amendment Bill?",
    o:["Both, Upper and Lower House together","Lower House","Upper House","Both, Upper and Lower House separately"] },
  { orig:86, s:MATH, a:2,
    q:"What is the square root of 108900?",
    o:["230","330","270","370"] },
  { orig:88, s:SCI, a:3,
    q:"Which gas is produced when a metal reacts with water?",
    o:["Oxygen","Chlorine","Hydrogen","Nitrogen"] },
  { orig:91, s:SCI, a:1,
    q:"An object starts its motion from rest. It gains a speed of 5 m/s in 2 s. Its acceleration will be ______.",
    o:["2.5 m/s²","1 m/s²","2 m/s²","0.4 m/s²"] },
  { orig:92, s:REA, a:3,
    q:"Which of the following assumptions is/are implied from the below statement?\n\n\"I am eagerly awaiting to present this year's report to the top management\", said the area sales manager to his colleague.\n\nAssumptions:\nI. The company has some new acquisitions in that area.\nII. The manager has vital information that would make an impression on the top management.",
    o:["Only assumption I is implicit","Both assumptions I and II are implicit","Neither assumption I nor II is implicit","Only assumption II is implicit"] },
  { orig:93, s:SCI, a:3,
    q:"A basic event in protein synthesis is the creation of a/an ______.",
    o:["DNA copy","RNA copy","mRNA copy","DNA and RNA copy"] },
  { orig:94, s:GA, a:1,
    q:"Name the Indian woman cricketer who became the highest wicket taker in Women's ODIs as of 27th June 2017?",
    o:["Jhulan Goswami","Devika Vaidya","Mansi Joshi","Soni Yadav"] },
  { orig:97, s:GA, a:3,
    q:"With a view to assisting outstanding sportspersons of yesteryears, living in indigent circumstances who had won glory for the country in sports, ______ was set up in 1982.",
    o:["National Welfare Club for Sportsperson","National Promotion Scheme for Sportsperson","National Welfare Fund for Sportsperson","National Pension Scheme for Sportsperson"] },
  { orig:99, s:REA, a:3,
    q:"Consider the given statement and decide which of the following assumptions is/are implicit in the statement.\n\nStatement: Laughter therapy is the best alternative therapy.\n\nAssumptions:\nI. Laughter is simple and universal.\nII. Laughter generates happy hormones in our system that boosts immune system.",
    o:["Neither I nor II is implicit","Only I is implicit","Both I and II are implicit","Only II is implicit"] },
  { orig:100, s:MATH, a:4,
    q:"Kazipet, which has a population of 4000, requires 9 litres of water per person per day. It has a cuboidal tank measuring 15 m × 8 m × 6 m. If the tank is full of water then for how many days will the water of this tank last?",
    o:["25 days","30 days","10 days","20 days"] },
];
