// Paper (26 Sep 2018, Shift-1) — bilingual English/Tamil. Image-based answer-key source.
// Answers from reliable green-tick decode (JSON). Kept 55/100.
// Tamil-only Qs translated to English where clean (59, 76); Tamil-garbled, figure-option,
// blank-option, lost-stem and unverifiable-cipher Qs dropped.
const MATH = 'Mathematics';
const REA  = 'General Intelligence & Reasoning';
const SCI  = 'General Science';
const GA   = 'General Awareness & Current Affairs';

export const PART = [
  { orig:4, s:REA, a:2,
    q:"Latika fills petrol in her car once in three days. This week she puts petrol on a Wednesday, on which of the following days will she fill petrol in the following week?",
    o:["Sunday and Saturday","Tuesday and Friday","Tuesday and Saturday","Monday and Friday"] },
  { orig:5, s:MATH, a:1,
    q:"The sum of the lengths of the edges of a cube is equal to one eighth of the perimeter of a square. If the numerical value of the volume of the cube is equal to the numerical value of the area of the square, then the length of one edge of the cube is:",
    o:["576 units","336 units","432 units","288 units"] },
  { orig:7, s:GA, a:4,
    q:"Which city had India's first helicopter-taxi service?",
    o:["Chennai","Mumbai","Delhi","Bengaluru"] },
  { orig:8, s:GA, a:2,
    q:"Who is the Chief Minister of Telangana as of March 2018?",
    o:["N. Chandra Babu Naidu","K. Chandrashekar Rao","K. Palani Swamy","K. Taraka Rama Rao"] },
  { orig:10, s:MATH, a:2,
    q:"In a test, Paranjoy secured 272 marks that was also equivalent to obtaining 64% marks. How many marks was the test out of?",
    o:["450","425","475","440"] },
  { orig:11, s:MATH, a:1,
    q:"The ratio of 30 min to 40 min is written as:",
    o:["3 : 4","1 : 20","1 : 80","4 : 3"] },
  { orig:14, s:SCI, a:4,
    q:"The mass of an object is 20 kg. What is the weight of that object on the Earth? [g = 9.8 ms⁻²]",
    o:["−196 N","19.6 N","1960 N","196 N"] },
  { orig:15, s:GA, a:4,
    q:"Which of the following channels won the award for the 'Best News Channel – Hindi' at the 17th Indian Television Academy Awards?",
    o:["ABP News","Zee News","NDTV India","Aaj Tak"] },
  { orig:19, s:GA, a:1,
    q:"As of 2018, who is the sports minister of India?",
    o:["Rajyavardhan Singh Rathore","Amarendra Kumar Dube","Vijay Goel","Rahul Bhatnagar"] },
  { orig:22, s:REA, a:1,
    q:"Pallavi's house faces East. On entering her home, you will find a gallery to the right-hand side and on moving 90° clockwise from the gallery there is a balcony. Which direction does the balcony face?",
    o:["East","North","South","West"] },
  { orig:23, s:MATH, a:3,
    q:"If ₹6,000 is invested at the rate of 20% per annum, compounded half-yearly, then the amount after 18 months will be:",
    o:["₹7,800","₹7,928","₹7,986","₹7,896"] },
  { orig:24, s:SCI, a:3,
    q:"The bleaching agent present in the bleaching powder is:",
    o:["Bromine","Iodine","Chlorine","Hydrogen"] },
  { orig:25, s:GA, a:2,
    q:"In 2017, Indian men's and women's hockey teams both earned the top spot in which international tournament?",
    o:["The Commonwealth Games","The Asia Cup","The Hockey World Cup","The Hockey Champions Trophy"] },
  { orig:26, s:SCI, a:3,
    q:"Trapped heat inside the Earth's surface is known as:",
    o:["Fossil energy","Tidal energy","Geo-thermal energy","Nuclear energy"] },
  { orig:28, s:SCI, a:1,
    q:"Sound travels fastest in which of the following mediums?",
    o:["Solids","Gases","Liquids","Vacuum"] },
  { orig:29, s:SCI, a:3,
    q:"When the copper metal is dipped in the solution of zinc sulphate, then:",
    o:["Zinc oxide is formed","Water is formed","No reaction takes place","Copper sulphate is formed"] },
  { orig:33, s:GA, a:3,
    q:"Sunderbans is the home of the ______.",
    o:["Tiger","Bison","Royal Bengal Tiger","Spotted Deer"] },
  { orig:35, s:SCI, a:2,
    q:"The objects that produce their own light are called as:",
    o:["Nonluminous objects","Luminous objects","Translucent objects","Transparent objects"] },
  { orig:36, s:REA, a:2,
    q:"Viki cycles 2 km towards West and then turns right and cycles 1 km. In which direction is he with respect to his initial position?",
    o:["North-East","North-West","South-East","South-West"] },
  { orig:37, s:REA, a:3,
    q:"Find the next term in the given series.\n1200, 600, 300, ______.",
    o:["75","500","150","250"] },
  { orig:39, s:MATH, a:4,
    q:"S is younger than R by 7 years. If their ages are in the respective ratio of 7 : 9, how old is S?",
    o:["28 years","18 years","16 years","24.5 years"] },
  { orig:41, s:SCI, a:3,
    q:"______ is a halogen.",
    o:["Magnesium","Krypton","Chlorine","Sodium"] },
  { orig:43, s:GA, a:2,
    q:"Which of the following project's objective is to ensure the operational turnaround of the banks and stressed companies?",
    o:["Project Samridhi","Project Sashakt","Project Parivartan","Project Sukanya"] },
  { orig:44, s:MATH, a:1,
    q:"0.36 + 0.284 ÷ 0.4 × 0.8 − 0.038 = ?",
    o:["0.89","1.25","0.548","1.2"] },
  { orig:45, s:REA, a:3,
    q:"Find the next term in the below series.\n26, 29, 33, 38, ______.",
    o:["50","42","44","54"] },
  { orig:46, s:GA, a:3,
    q:"Who is the first chairman of the Goods and Services Tax (GST) Council?",
    o:["Rajnath Singh","Suresh Prabhu","Arun Jaitley","Prakash Javadekar"] },
  { orig:48, s:SCI, a:4,
    q:"An object with a mass of 100 kg is accelerated uniformly from a velocity of 5 ms⁻¹ to 17 ms⁻¹ in 6 s. The magnitude of force exerted on the object is ______.",
    o:["200 ms⁻²","200 ms⁻¹","200 Pa","200 N"] },
  { orig:57, s:REA, a:2,
    q:"Rod is to metal in the same way flute is to:",
    o:["sound","bamboo","player","hole"] },
  { orig:59, s:SCI, a:4,
    q:"______ cells create various different permanent tissues.",
    o:["Collenchyma","Sclerenchyma","Parenchyma","Meristematic"] },
  { orig:60, s:GA, a:1,
    q:"'The International Women's Day' is celebrated every year on:",
    o:["March 8","December 9","May 9","July 8"] },
  { orig:63, s:SCI, a:2,
    q:"In sexual reproduction, the parents contributes:",
    o:["One fourth of its genes","Half of its genes","Three fourth of its genes","All of its genes"] },
  { orig:65, s:GA, a:3,
    q:"The name 'Bharata' is used as a designation for India in the Indian Constitution referencing the ancient mythological emperor, Bharata, whose story is told, in part, in the Indian epic ______.",
    o:["the Ramayana","the Upanishads","the Mahabharata","the Geeta"] },
  { orig:66, s:MATH, a:2,
    q:"(3 − 0.2) / (0.1 × (3 + 0.2)) = ?",
    o:["0.875","8.75","0.0875","87.5"] },
  { orig:67, s:MATH, a:1,
    q:"A grocery shop procures 600 bottles of packaged juice from two different vendors. 20% of the lot is from Vendor-1 and 80% is from Vendor-2. The cost per bottle is ₹25. After reviewing the lot from Vendor-2, the grocer finds that 25% of the lot had just a day's shelf life. He decides to return the lot back. How much money will he get back from Vendor-2?",
    o:["₹3,000","₹3,750","₹3,500","₹4,000"] },
  { orig:70, s:MATH, a:4,
    q:"24 experts can do as much work as 40 trainees in a given period of time. A piece of work can be done by 9 experts and 25 trainees. How many trainees alongside 12 experts would one need to complete a similar work in the same duration of time?",
    o:["22","18","24","20"] },
  { orig:72, s:SCI, a:2,
    q:"______ is used as a catalyst in the hydrogenation of vegetable oil.",
    o:["Lead","Nickel","Helium","Hydrogen"] },
  { orig:74, s:MATH, a:3,
    q:"One pipe can fill an empty cistern in 7/4 hours while another can drain the cistern when full in 21/8 hours. Both the pipes were turned on when the cistern was two-thirds empty. How long will it take for the cistern to be full?",
    o:["3 hours 45 minutes","3 hours 20 minutes","3 hours 30 minutes","3 hours 15 minutes"] },
  { orig:75, s:SCI, a:2,
    q:"In 23.3 g of zinc, the number of moles is:",
    o:["0.53","0.35","0.37","0.25"] },
  { orig:76, s:SCI, a:2,
    q:"When an object falls freely on its own, the ______ energy along its path can increase at every point.",
    o:["Potential energy","Kinetic energy","Chemical energy","Mechanical energy"] },
  { orig:77, s:SCI, a:3,
    q:"Which of the following is an olfactory indicator?",
    o:["Soap","Rose","Clove","Turmeric"] },
  { orig:78, s:GA, a:3,
    q:"The famous tourist attraction Victoria Memorial is in ______.",
    o:["Arunachal Pradesh","Gujarat","West Bengal","Maharashtra"] },
  { orig:79, s:SCI, a:3,
    q:"______ element has three orbits with 8 electrons in the outer shell.",
    o:["Xe","Kr","Ar","Ne"] },
  { orig:85, s:GA, a:4,
    q:"In the medieval period, the Sharqi Kings built the Atala Mosque in ______.",
    o:["Kashmir","Malwa","Gujarat","Jaunpur"] },
  { orig:86, s:REA, a:2,
    q:"29th of November 2018 is a Thursday. 29th of November 2021 will be a ______.",
    o:["Sunday","Monday","Saturday","Friday"] },
  { orig:87, s:GA, a:3,
    q:"Name the Indian batswoman who secured 2nd position in the ICC One Day International Cricket rankings list released recently in 2017?",
    o:["Mona Meshram","Veda Krishnamurthy","Mithali Raj","Harmanpreet Kaur"] },
  { orig:88, s:GA, a:3,
    q:"Who became youngest girl in the world to conquer Mount Everest and Mount Elbrus (highest peak Europe)?",
    o:["Bachendri Pal","Arunima Sinha","Malavath Poorna","Krushnaa Patil"] },
  { orig:89, s:GA, a:1,
    q:"Black Revolution is related to production of ______.",
    o:["petroleum","black roses","coal","black grapes"] },
  { orig:91, s:MATH, a:2,
    q:"A bakery sells breads, cakes, puffs and whole grain biscuits. Every day, they use 9 kg of all-purpose flour to make the aforementioned items. If 20% of all-purpose flour is used for making cakes, what is the actual quantity (in grams) of all-purpose flour used for making cakes?",
    o:["1000","1800","2000","1500"] },
  { orig:92, s:MATH, a:3,
    q:"Find the HCF of 6xy²z, 8x²y²z², 12x²y³z³.",
    o:["2xyz","4xy²z","2xy²z","3xy²z"] },
  { orig:94, s:GA, a:2,
    q:"Who was the second Indian women footballer to win the Arjuna Award?",
    o:["Aditi Chauhan","Oinam Bembem Devi","Bala Devi","Mithali Raj"] },
  { orig:95, s:GA, a:1,
    q:"Name the Chief Justice of India appointed in 2017?",
    o:["Dipak Misra","J. Chalameswar","Madan Lokur","Ranjan Gogoi"] },
  { orig:96, s:SCI, a:3,
    q:"______ is a monocot plant.",
    o:["Carrot","Daisy","Garlic","Rose"] },
  { orig:98, s:SCI, a:4,
    q:"The guard cells swell when ______ flows into them causing the stomatal pore to open.",
    o:["enzyme","hormone","chemical","water"] },
  { orig:99, s:MATH, a:3,
    q:"The measurement of a brick is 20 cm by 12 cm by 8 cm. How many such bricks will be required to construct a wall 16.8 m in height, 2.5 m wide and 12 cm thick?",
    o:["2652","5262","2625","6252"] },
  { orig:100, s:SCI, a:2,
    q:"Water stored in a dam possesses:",
    o:["Electrical energy","Potential energy","Gravitational energy","Kinetic energy"] },
];
