// Paper (27 Sep 2018, Shift-1) — English paper. Source: Adda247 answer-key PDF
// (green-tick = correct option), read page-by-page (docx XML was a scrambled
// multi-column table, so the PDF render was used instead). Kept 87/100.
// Dropped (figure/symbol-pattern/table-image or officially-cancelled):
//   5,42,62,63,69,80,84,88,90,91,92,95,99.
const MATH = 'Mathematics';
const REA  = 'General Intelligence & Reasoning';
const SCI  = 'General Science';
const GA   = 'General Awareness & Current Affairs';

export const PART = [
  { orig:1, s:REA, a:4,
    q:"You are given a question and two statements. Decide which of the statements is/are sufficient to answer the question.\n\nQuestion: What is the total age of the sisters 10 years from now?\n\nStatements:\nI. Liza is 22 years old now.\nII. Liza's sister's age is twice that of 1/4th of the age of Liza.",
    o:["Statement 1 alone is sufficient","Statements 1 and 2 together are not sufficient","Statement 2 alone is sufficient","Statements 1 and 2 together are sufficient"] },
  { orig:2, s:GA, a:1,
    q:"Who has won the Best Actor award in the 90th Oscar awards 2018?",
    o:["Gary Oldman","Denzel Washington","Daniel Day Lewis","Daniel Kaluuya"] },
  { orig:3, s:SCI, a:1,
    q:"A person clapped his hands near a cliff and heard the echo after 6 s. The distance of the cliff from the person is: [take v = 346 ms⁻¹]",
    o:["1038 m","1083 m","2076 m","2706 m"] },
  { orig:4, s:SCI, a:4,
    q:"A car accelerates uniformly from 18 kmh⁻¹ to 72 kmh⁻¹ in 5 s. The acceleration of the car is:",
    o:["3 ms²","10.8 ms⁻²","10.8 ms²","3 ms⁻²"] },
  { orig:6, s:SCI, a:2,
    q:"What is the percentage of oxygen in Al₂(SO₄)₃?",
    o:["57.7%","56.1%","53.1%","52.6%"] },
  { orig:7, s:REA, a:1,
    q:"Given is a question followed by two arguments. Decide which of the arguments is/are strong with respect to the question.\n\nQuestion: Should we avoid overuse of air conditioners?\n\nArguments:\nI. Yes, it weakens the human system.\nII. No, the comfort cannot be forsaken.",
    o:["Only argument I is strong","Both arguments I and II are strong","Only argument II is strong","Neither argument I nor II is strong"] },
  { orig:8, s:GA, a:2,
    q:"Prime Minister Narendra Modi laid the foundation stone of Char Dham highway development project or Chardham Mahamarg Vikas Pariyojna at ______.",
    o:["Rishikesh","Dehradun","Manikaran","Haridwar"] },
  { orig:9, s:REA, a:2,
    q:"Pond is related to Water in the same way as Mountain is related to:",
    o:["Birds","Rocks","Animals","Climb"] },
  { orig:10, s:GA, a:4,
    q:"Who became the first Indian woman to win the Korea open series in Badminton?",
    o:["Saina Nehwal","Jwala Gutta","Ashwini Ponnappa","P. V. Sindhu"] },
  { orig:11, s:REA, a:2,
    q:"You are given a question and two statements. Decide which of the statements is/are sufficient to answer the question.\n\nQuestion: Among the bags A, B, C and D which is the lighter bag?\n\nStatements:\nI. B is two times A.\nII. A is lighter than C and D.",
    o:["Statement 2 alone is sufficient","Statement 1 and 2 together are necessary","Statement 1 alone is sufficient","Statement 1 and 2 are not sufficient to solve"] },
  { orig:12, s:GA, a:3,
    q:"Name the country which won the 2017 Women's Hockey Asia Cup title?",
    o:["Nepal","Pakistan","India","Bangladesh"] },
  { orig:13, s:MATH, a:4,
    q:"The median of the numbers 14, 12, 12, 16, 13 and 18 is:",
    o:["13","14","14.5","13.5"] },
  { orig:14, s:GA, a:2,
    q:"PM Modi's Birthday has been celebrated as ______ across India.",
    o:["Kisan Diwas","Sewa Diwas","Hindi Diwas","Bal Diwas"] },
  { orig:15, s:GA, a:2,
    q:"The Chola kings were prolific temple builders who built the ______ temple at Tanjavur.",
    o:["Brahmeshvara","Brihadeesvara","Lingaraja","Dilwara"] },
  { orig:16, s:SCI, a:2,
    q:"______ gas is used as an illuminating gas.",
    o:["Methyl","Propane","Butene","Ethyne"] },
  { orig:17, s:MATH, a:4,
    q:"80 ÷ [48 − {56 − (60 − 36 ÷ 12 × 4)}] =",
    o:["5","8","4","2"] },
  { orig:18, s:REA, a:2,
    q:"Read the given statement(s) and conclusions carefully and select which of the conclusions logically follow(s) from the statement.\n\nStatement: \"Kirti played a very good shot on the pitch,\" says a friend to Sajit.\n\nConclusions:\nI. Sajit likes cricket.\nII. Kirti is a good player.",
    o:["Conclusion I alone follows","Conclusion II alone follows","Neither I nor II follows","Both the conclusions follow"] },
  { orig:19, s:MATH, a:3,
    q:"¾ + {¾ + ¾ ÷ (¾ + ¾)} = ?",
    o:["¾","1","2","2¾"] },
  { orig:20, s:MATH, a:2,
    q:"A water tank is 2/5 th full. Inlet A can fill the tank in 12 minutes while an outlet pipe B can empty it in 6 minutes. If both the pipes are open, how long will it take to empty or fill the tank completely?",
    o:["It fills in 4.8 min","It empties in 4.8 min","It fills in 5.6 min","It empties in 5.6 min"] },
  { orig:21, s:MATH, a:2,
    q:"38% of a number is 133. What is the number?",
    o:["340","350","360","355"] },
  { orig:22, s:GA, a:3,
    q:"Who among the following had been roped in June 2017 by the Union Government of India to promote GST?",
    o:["Sachin Tendulkar","Salman Khan","Amitabh Bachchan","Aishwarya Rai Bachchan"] },
  { orig:23, s:MATH, a:1,
    q:"Find the square root of 15625.",
    o:["125","145","150","135"] },
  { orig:24, s:REA, a:4,
    q:"Complete the number series by choosing the missing terms from the options.\n32, 64, 256, 1536, ?, 122880, 1474560.",
    o:["122860","12268","12285","12288"] },
  { orig:25, s:MATH, a:2,
    q:"If tanα = √3 + 2, then the value of tanα − cotα is",
    o:["2","2√3","√3 − 2","4"] },
  { orig:26, s:MATH, a:4,
    q:"In a triangle XYZ, M is the midpoint of YZ, ∠XMZ = 32° and ∠XYZ = 16°. The measure of ∠XZY is:",
    o:["68°","84°","81°","74°"] },
  { orig:27, s:SCI, a:3,
    q:"Soft drinks contain:",
    o:["Oxalic acid","Tartaric acid","Carbonic acid","Citric acid"] },
  { orig:28, s:MATH, a:4,
    q:"Raghu has invested ₹1000 and received ₹1300 at 6% per annum simple interest after X years. Find the value of X.",
    o:["4 years","3 years","2 years","5 years"] },
  { orig:29, s:GA, a:4,
    q:"Thorn Forests are found in ______.",
    o:["Kashmir","Kerala","Sikkim","Rajasthan"] },
  { orig:30, s:SCI, a:3,
    q:"Bending of light rays in denser medium is termed as:",
    o:["Reflection","Dispersion","Refraction","Deflection"] },
  { orig:31, s:MATH, a:4,
    q:"In a shop 4.5% of 1500 kg toor dal was sold. Find the quantity sold.",
    o:["64.5 kg","63.5 kg","70 kg","67.5 kg"] },
  { orig:32, s:REA, a:3,
    q:"Consider the given statement(s) and decide which of the given assumption(s) is/are implicit in the statement.\n\nStatement: School students are more influenced by their faculty nowadays.\n\nAssumptions:\nI. School students consider their faculty as role models.\nII. More time is spent at schools by students.",
    o:["Neither I nor II is implicit","Only II is implicit","Only I is implicit","Either I or II is implicit"] },
  { orig:33, s:SCI, a:1,
    q:"An object travels 23 m in 3 s and then another 15 m in 2 s. What is the average speed of the object?",
    o:["7.6 ms⁻¹","7.6 s⁻¹","8.0 ms⁻¹","7.6 m"] },
  { orig:34, s:REA, a:3,
    q:"Find the next term in the following series:\nX24C, V22E, T20G, ______",
    o:["RI19","R19I","R18I","RI18"] },
  { orig:35, s:MATH, a:2,
    q:"Pipe A is an inlet pipe that can fill an empty cistern in 69 hours. Pipe B can drain the filled cistern in 46 hours. When the cistern was filled the two pipes are opened one at a time for an hour each, starting with Pipe B. How long will it take for the cistern to be empty?",
    o:["11 days 10 hours","11 days 7 hours","11 days 12 hours","1 days 13 hours"] },
  { orig:36, s:SCI, a:1,
    q:"When a constant force acts on an object with a mass of 8 kg for a duration of 3 s, it increases the object's velocity from 4 ms⁻¹ to 6 ms⁻¹. What is the magnitude of the applied force?",
    o:["5.33 N","4.33 N","6.33 N","3.33 N"] },
  { orig:37, s:REA, a:1,
    q:"Find the next term in the following series:\nZ26, X24, V22, ______",
    o:["T20","W23","K15","J10"] },
  { orig:38, s:SCI, a:1,
    q:"An object of 10 kg is moving with a speed of 2 m/s. The kinetic energy of the object is:",
    o:["20 J","5 J","10 J","40 J"] },
  { orig:39, s:MATH, a:3,
    q:"If a is positive and a² + 1/a² = 7, then a³ + 1/a³ =",
    o:["21","3√7","18","7√7"] },
  { orig:40, s:SCI, a:4,
    q:"______ elements have the largest atoms.",
    o:["F","O","H","Li"] },
  { orig:41, s:GA, a:4,
    q:"West Bengal shares boundaries with ______ countries.",
    o:["2","4","1","3"] },
  { orig:43, s:SCI, a:4,
    q:"If a person moves a trolley for a distance of 10 m with a force of 50 N, then the work done is:",
    o:["0.2 J","5 J","20 J","500 J"] },
  { orig:44, s:MATH, a:4,
    q:"A and B can complete a task in 1.5 days. However, A had to leave a few days before the task was completed and hence it took 2 days in all to complete the task. If A alone could complete the work in 2.625 days, how many days before the work getting over did A leave?",
    o:["1.125","0.625","0.375","0.875"] },
  { orig:45, s:SCI, a:4,
    q:"A/An ______ tissue is formed beneath the skin and between internal organs.",
    o:["Epithelial","Nervous","Muscular","Adipose"] },
  { orig:46, s:REA, a:1,
    q:"If MEAT is coded as 135120, then what will be the code for ZEBRA?",
    o:["2652181","2652191","2662181","2662191"] },
  { orig:47, s:GA, a:2,
    q:"Who among the following hosted the Hindi version of \"Bigg Boss-11\"?",
    o:["Aamir Khan","Salman Khan","Shilpa Shetty","Farhan Akhtar"] },
  { orig:48, s:SCI, a:4,
    q:"______ is the property of attracting electrons by the halogen atoms in a molecule.",
    o:["Electron affinity","Electropositivity","Electrochemistry","Electronegativity"] },
  { orig:49, s:GA, a:2,
    q:"The headquarter of the Board of Control for Cricket in India (BCCI) is located in:",
    o:["Delhi","Mumbai","Chennai","Kolkata"] },
  { orig:50, s:SCI, a:1,
    q:"Which of the following inert gases is placed in period 4 of the periodic table?",
    o:["Kr","Rn","Xe","Ar"] },
  { orig:51, s:REA, a:2,
    q:"In a code language, AILMENT is written as 1923540. What is the code for DISEASE?",
    o:["4985195","4995195","4905195","4995196"] },
  { orig:52, s:MATH, a:1,
    q:"Sabrina travelled 8 km/hr on foot and 13 km/hr on cycle. She travelled a distance of 84 km in 8 hours. For how many hours did she cycle?",
    o:["4","5","3","2"] },
  { orig:53, s:REA, a:2,
    q:"Venu is the Son of Avani and Amit is the son of Avani's brother. How is Amit's Mother related to Venu?",
    o:["Sister","Maternal aunt","Paternal aunt","Cousin"] },
  { orig:54, s:SCI, a:4,
    q:"Who is considered as the father of taxonomy?",
    o:["Darwin","Einstein","Mandelbrot","Linnaeus"] },
  { orig:55, s:REA, a:3,
    q:"5th January 2018 was a Friday. Which of the following years will also have 5th January on a Friday?",
    o:["2022","2020","2024","2023"] },
  { orig:56, s:GA, a:2,
    q:"As per RBI Annual Report 2016-17, what is the estimated value of demonetised banknotes received?",
    o:["₹12.25 lakh crore","₹15.28 lakh crore","₹19.48 lakh crore","₹13.35 lakh crore"] },
  { orig:57, s:GA, a:3,
    q:"Who among the following was crowned with the Miss World 2017 title?",
    o:["Andrea Meza","Rolene Strauss","Manushi Chillar","Aurore Kichenin"] },
  { orig:58, s:MATH, a:3,
    q:"For the data given below, find the sum of mode, median and mean.\n6, 3, 8, 4, 3, 11, 7, 4, 5, 4.",
    o:["13.5","13","14","14.5"] },
  { orig:59, s:MATH, a:3,
    q:"Vishal is 20 years younger to Arya. Twelve years hence Arya's age will be 1.25 times that of Vishal. Arya is now ______ years old.",
    o:["78","68","88","72"] },
  { orig:60, s:REA, a:1,
    q:"Read the given statement(s) and conclusions carefully and select which of the conclusions logically follow(s) from the statement(s).\n\nStatement: Looking at Limay's new watch, Nita comments, \"Ooh, that's so awesome. Where did you buy it from?\"\n\nConclusions:\nI. Limay's watch is attractive.\nII. Nita wants to know where to buy a similar watch from.",
    o:["Both the conclusions follow","Conclusion II alone follows","Neither I nor II follows","Conclusion I alone follows"] },
  { orig:61, s:GA, a:3,
    q:"In ______, Sher Khan (SherShah) attacked Bengal and defeated Ghiyashuddin Shah.",
    o:["1358","1583","1538","1540"] },
  { orig:64, s:REA, a:1,
    q:"In a code language, FATE is written as 61205. What is the code for LEAN?",
    o:["125114","125115","126114","135114"] },
  { orig:65, s:MATH, a:2,
    q:"Which of the following numbers is irrational?",
    o:["¹⁰√1024","⁴√1024","√1024","⁵√1024"] },
  { orig:66, s:REA, a:1,
    q:"Find the next term in the given series.\nB2, K12, T72, ______",
    o:["C432","A434","A432","C434"] },
  { orig:67, s:GA, a:1,
    q:"The famous activist Irom Chanu Sharmila is better known as 'The Iron Lady of ______'.",
    o:["Manipur","Mizoram","Nagaland","Tripura"] },
  { orig:68, s:SCI, a:2,
    q:"______ helps the eye to adjust the focal length of the lens.",
    o:["Lens","Ciliary body","Retina","Entire eye ball"] },
  { orig:70, s:GA, a:4,
    q:"Name the Chief Minister of Telangana who was honoured with the Global Agricultural Leadership Award 2017.",
    o:["Siddaramaiah","K. T. Rama Rao","N. Chandrababu Naidu","K. Chandra Shekhar Rao"] },
  { orig:71, s:GA, a:1,
    q:"What is the full form of ASSOCHAM?",
    o:["Associated Chambers of Commerce and Industry","Association of Commerce","Associated Commerce","Associated Chambers in India"] },
  { orig:72, s:GA, a:3,
    q:"Name the Bollywood actor who received Kala Ratan Award in March 2017?",
    o:["Naseeruddin Shah","Akshay Kumar","Anupam Kher","Jitendra"] },
  { orig:73, s:SCI, a:4,
    q:"Where the mature sperm are produced?",
    o:["Scrotum","Vas deferens","Prostate gland","Testes"] },
  { orig:74, s:SCI, a:4,
    q:"Asexual reproduction takes place in:",
    o:["Plants","Higher animals","Lower animals","Lower animals and plants"] },
  { orig:75, s:MATH, a:4,
    q:"Triheni had to travel 175 km in 3.5 hours. However, she travelled at the rate of 58 km/hr for 2.5 hours and then rested for 20 minutes before completing the journey. If Triheni managed to reach on time, her speed during the last stretch would have been ______.",
    o:["36 km/hr","30 km/hr","42.5 km/hr","45 km/hr"] },
  { orig:76, s:GA, a:2,
    q:"Who among the following was sworn in as the Chief Minister of Manipur in 2017?",
    o:["M Koireng Singh","N Biren Singh","Longjam Thambou","M Alimuddin Singh"] },
  { orig:77, s:SCI, a:2,
    q:"An object travels 24 m in 3 s and then another 15 m in 2 s. What is the average speed of the object?",
    o:["7.8 s⁻¹","7.8 ms⁻¹","8.0 m","6.67 ms⁻¹"] },
  { orig:78, s:MATH, a:1,
    q:"(−12)[11 + {7 × (−3)}] ÷ [4{13 − (−3) × (−6)}] =",
    o:["−6","−4","4","−2"] },
  { orig:79, s:SCI, a:4,
    q:"An object having the capability to do work is said to possess:",
    o:["Inertia","Force","Pressure","Energy"] },
  { orig:81, s:SCI, a:1,
    q:"______ is displaced when zinc is added to the solution of copper sulphate.",
    o:["Copper","Hydrogen","Zinc","Sulphate"] },
  { orig:82, s:SCI, a:2,
    q:"Atomic radius is measured in:",
    o:["Micrometres","Nanometres","Millimetres","Centimetres"] },
  { orig:83, s:SCI, a:1,
    q:"______ compound is used as a drying agent.",
    o:["Calcium oxide","Calcium carbide","Gypsum","Calcium carbonate"] },
  { orig:85, s:REA, a:2,
    q:"Consider the given statement(s) and decide which of the given assumption(s) is/are implicit in the statement.\n\nStatement: \"The use of antibiotic tablets, destabilises the gut bacteria\".\n\nAssumptions:\nI. There are friendly bacteria in the gut.\nII. Gut health is foremost for overall health.",
    o:["Both I and II are implicit","Only I is implicit","Only II is implicit","Neither I nor II is implicit"] },
  { orig:86, s:SCI, a:1,
    q:"A mass of 20 kg is at a height of 8 m above the ground. Then the potential energy possessed by the body is: [Given g = 9.8 ms⁻²]",
    o:["1568 J","1568 C","1568 W","1568 N"] },
  { orig:87, s:SCI, a:4,
    q:"1 kWH = ______ J",
    o:["3.6 × 10⁻⁸","3.6 × 10⁻⁶","3.6 × 10⁸","3.6 × 10⁶"] },
  { orig:89, s:MATH, a:2,
    q:"The price per kg of vegetables for three months is — January: Year 1 ₹40, Year 2 ₹35; February: Year 1 ₹40, Year 2 ₹50; March: Year 1 ₹40, Year 2 ₹35. What is the average price difference per kg (in ₹) for vegetables between the two years for the three months?",
    o:["Average price of vegetables in Year 1 is less than that in Year 2.","There is no difference in the average price.","Average price of vegetables in Year 2 is less than that in Year 1.","We cannot compare the prices."] },
  { orig:93, s:REA, a:1,
    q:"In the year 2016, there were 52 weeks and P days. Find the value of P.",
    o:["2","4","3","5"] },
  { orig:94, s:MATH, a:2,
    q:"Which of the fractions given below is not equal to 4/11?",
    o:["32/88","84/209","64/176","20/55"] },
  { orig:96, s:MATH, a:1,
    q:"Alarms from 3 different clocks sound after every 2, 4 and 6 hours, respectively. If the clocks are started at the same time, how many times do the alarms ring together in 3 days?",
    o:["6","3","9","2"] },
  { orig:97, s:REA, a:3,
    q:"Meet starts cycling early in the morning, facing the Sun. After some time, he takes a 45° turn to his left and then again turns 80° towards his left. In which direction is he now with respect to his initial position?",
    o:["South-East","South-West","North-West","North-East"] },
  { orig:98, s:GA, a:3,
    q:"As of August 2018, what is the portfolio held by the current Union Minister Ravi Shankar Prasad?",
    o:["Human Resource Development","Petroleum","Law and Telecommunications","Coal"] },
  { orig:100, s:MATH, a:2,
    q:"(−18)[36 ÷ {7 − (−2)}] ÷ (−4){19 − (−3) × (−5)} = ?",
    o:["−4.5","4.5","2.5","−2.5"] },
];
