// Paper (28 Sep 2018, Shift-1) — English paper. Source: Adda247 answer-key PDF
// (green-tick = correct option), read page-by-page. Kept 85/100.
// Dropped (figure/symbol-pattern or officially-cancelled "discrepancy" questions):
//   14,18,20,24,27,31,36,47,52,54,59,69,70,75,90.
const MATH = 'Mathematics';
const REA  = 'General Intelligence & Reasoning';
const SCI  = 'General Science';
const GA   = 'General Awareness & Current Affairs';

export const PART = [
  { orig:1, s:SCI, a:4,
    q:"An object travels 10 m in 4 s and then another 14 m in 2 s. What is the average speed of the object?",
    o:["4.5 ms⁻¹","4 m","4 s⁻¹","4 ms⁻¹"] },
  { orig:2, s:SCI, a:1,
    q:"The molten material mixed with gases in the middle of the Earth is called:",
    o:["Magma","Helium","Core","Lava"] },
  { orig:3, s:SCI, a:3,
    q:"How many groups and periods are present in the Modern Periodic Table?",
    o:["8 groups and 6 periods","18 groups and 9 periods","18 groups and 7 periods","7 groups and 10 periods"] },
  { orig:4, s:MATH, a:4,
    q:"What is the sum of the reciprocals of the values of zeroes of the polynomial 6x³ + 3x² − 5x + 1?",
    o:["2","3","4","5"] },
  { orig:5, s:REA, a:3,
    q:"Find the odd one out.\nA) O15   B) C3   C) G7   D) N15",
    o:["C","B","D","A"] },
  { orig:6, s:SCI, a:4,
    q:"What is the valency of copper in cuprous oxide?",
    o:["4","3","2","1"] },
  { orig:7, s:MATH, a:1,
    q:"315 marbles are distributed among Aman, Ashok and Alok in the ratio 7 : 3 : 5, respectively. How many more marbles did Aman get compared to Ashok?",
    o:["84","42","147","63"] },
  { orig:8, s:SCI, a:4,
    q:"______ does NOT contain carbonyl group.",
    o:["Aldehyde","Carboxyl acid","Ketone","Ethanol"] },
  { orig:9, s:MATH, a:4,
    q:"One of the two inlet pipes works twice as efficiently as the other. The two, working alongside a drain pipe that can empty a cistern all by itself in 12 hours, can fill the empty cistern in 12 hours. How many hours will the less efficient inlet pipe take to fill the empty cistern by itself?",
    o:["9","15","12","18"] },
  { orig:10, s:GA, a:4,
    q:"The Battle of Plassey was fought on ______.",
    o:["23rd June 1557","23rd June 1657","23rd June 1857","23rd June 1757"] },
  { orig:11, s:REA, a:3,
    q:"Which assumptions are implied from the below statement?\n\nStatement: \"In 10 years, the real impact of unscrupulous use of plastics would be felt,\" says an ecologist.\n\nAssumptions:\nI. Plastic is non-decomposable.\nII. Plastic affects the ecological balance.",
    o:["Only assumption II is implicit","Only assumption I is implicit","Both I and II are implicit","Neither I nor II is implicit"] },
  { orig:12, s:SCI, a:4,
    q:"The point at which all rays converge is termed as ______.",
    o:["principle axis","pole","aperture","focus"] },
  { orig:13, s:REA, a:3,
    q:"If E and A are daughters of B and A is married to V, then how is V related to E?",
    o:["Son-in-law","Father-in-law","Brother-in-law","Mother-in-law"] },
  { orig:15, s:MATH, a:1,
    q:"4x² + kx + 5 is divisible by x + 1. The same expression is also divisible by:",
    o:["4x + 5","4x − 1","4x − 5","x − 5"] },
  { orig:16, s:MATH, a:1,
    q:"Garima and her sister together can paint the walls of their house in 45 days. If Garima alone did the job, it would have taken her 81 days. If the duo started painting together but Garima's sister had to leave 9 days before the completion of the work, how many days in all would it take the sisters to paint their house?",
    o:["49","48","52","50"] },
  { orig:17, s:SCI, a:2,
    q:"______ has the greatest electron affinity.",
    o:["Br","Cl","I","F"] },
  { orig:19, s:GA, a:4,
    q:"______ was the Finance Minister of the Mughal empire during Akbar's reign.",
    o:["Birbal","Raja Man Singh 1","Tansen","Raja Todar Mal"] },
  { orig:21, s:REA, a:1,
    q:"Read the statement below along with two conclusions.\n\nStatement: Naina asks for pen from Mahi.\n\nConclusions:\nI. Naina doesn't have a pen.\nII. Naina wants to write something.\n\nWhich conclusion(s) follow(s) the given statement?",
    o:["Both the conclusions follow","Conclusion I alone follows","Neither I nor II follows","Conclusion II alone follows"] },
  { orig:22, s:GA, a:3,
    q:"______ is the mobile application launched by the Ministry of Commerce and Industry to aid importers and exporters in the country.",
    o:["Niksat Mitra","Maitree Mitra","Niryat Mitra","Dikhat Mitra"] },
  { orig:23, s:MATH, a:4,
    q:"A year ago Akash's father's age was 9 times that of Akash. After 3 years his father's age will be 5 times that of his age. How old will Akash be next year?",
    o:["4 years","5 years","8 years","6 years"] },
  { orig:25, s:SCI, a:3,
    q:"______ mutation is NOT hereditary.",
    o:["Deletion","Insertion","Somatic","Duplication"] },
  { orig:26, s:MATH, a:1,
    q:"Which of the following is NOT a perfect square?",
    o:["1250","16641","2025","9801"] },
  { orig:28, s:GA, a:4,
    q:"Which Indian has been crowned Miss Teen Universe 2017 at Managua, the capital of Nicaragua?",
    o:["Neeru Chadha","Nisha Dutt","Simran Khosla","Srishti Kaur"] },
  { orig:29, s:SCI, a:2,
    q:"Voluntary muscles are contained in the ______.",
    o:["heart","hind limb","liver","lung"] },
  { orig:30, s:REA, a:3,
    q:"Choose the correct alternative to complete the pattern:\n1224364860, 1122334455, 1020304050, ______",
    o:["918273642","918273644","918273645","918273643"] },
  { orig:32, s:REA, a:2,
    q:"Consider the given statement(s) and decide which of the given assumption(s) is/are implicit in the statement.\n\nStatement: \"Tomorrow morning the hockey team will report by 9:00 am instead of 8:00 am for practise\" said the coach.\n\nAssumptions:\nI. That day coach had some other work at 8:00 am.\nII. They usually assemble for practice.",
    o:["Only I is implicit","Only II is implicit","Both I and II are implicit","Neither I nor II is implicit"] },
  { orig:33, s:SCI, a:4,
    q:"Which of the following group produces naked seeds?",
    o:["Angiosperms","Bryophyta","Thallophyte","Gymnosperms"] },
  { orig:34, s:REA, a:2,
    q:"Find the next term in the following series:\n31, 38, 44, 51, ______",
    o:["58","57","51","55"] },
  { orig:35, s:MATH, a:2,
    q:"The ratio of the area of a square to the area of a regular hexagon, having the same perimeter is:",
    o:["2 : 3","√3 : 2","1 : √3","4 : 3√3"] },
  { orig:37, s:REA, a:3,
    q:"What is the next term in this series?\nL, D, O, E, R, F, ?",
    o:["K","S","U","Q"] },
  { orig:38, s:GA, a:4,
    q:"The Electoral College who elects the President of India is formed by:",
    o:["Head of the Parliament","Governor","Former President","Elected members of the Parliament and the State Legislative Assemblies"] },
  { orig:39, s:SCI, a:3,
    q:"An element of atomic number 16 will belong to the ______ period of the periodic table.",
    o:["5th","6th","3rd","4th"] },
  { orig:40, s:SCI, a:4,
    q:"An electric bulb of 100 W is used 8 hours per day. The energy consumed by the bulb in one day is ______ units.",
    o:["800","80","8","0.8"] },
  { orig:41, s:GA, a:1,
    q:"As of February 2018, who was the spokesperson of the Indian Navy?",
    o:["Captain D. K. Sharma","Admiral Suresh Bhatt","Captain M. K. Sharma","Pranab Mukherjee"] },
  { orig:42, s:MATH, a:2,
    q:"Pipe C and D alone can fill a tank in 4 and 5 hours, respectively. If pipe C is closed after 3 hours and at the same time pipe D is opened, in how many hours will the tank get filled?",
    o:["0.8","1.25","1","1.5"] },
  { orig:43, s:MATH, a:1,
    q:"{52 − (9 − 2)} ÷ [3 × {1 + (−2) × (−2)}] = ?",
    o:["3","−9","9","−5"] },
  { orig:44, s:REA, a:4,
    q:"Nikhil meets a boy at the park. The boy identifies Nikhil as his father's younger brother. Nikhil is the boy's ______.",
    o:["father","maternal uncle","cousin","paternal uncle"] },
  { orig:45, s:GA, a:1,
    q:"Football was officially included as a competitive game in Olympics in:",
    o:["1908","1924","1916","1900"] },
  { orig:46, s:MATH, a:4,
    q:"What is the area of a triangle whose vertices are A(−4, −2), B(−3, −5) and C(3, −2)?",
    o:["12 sq units","10 sq units","7.5 sq units","10.5 sq units"] },
  { orig:48, s:SCI, a:2,
    q:"The Second Equation of Motion gives the relationship between ______ and Time.",
    o:["Acceleration","Position","Momentum","Velocity"] },
  { orig:49, s:SCI, a:3,
    q:"If two charged bodies having equal potential are connected through a conducting wire, then:",
    o:["magnetic induction flows","current flows from positive to negative","current will not flow","current will flow from negative to positive"] },
  { orig:50, s:GA, a:2,
    q:"Who among the following won the Lion of Indian Entertainment award at the 17th edition of the Indian Television Academy Awards 2017?",
    o:["Jitendra","Ekta Kapoor","Siddharth Roy Kapur","Shobha Kapoor"] },
  { orig:51, s:REA, a:2,
    q:"V is the daughter of MX and N is the daughter of NX. MX and NX have the same father. V and N are:",
    o:["Sister-in-law","Cousins","Paternal Aunt","Maternal Aunt"] },
  { orig:53, s:GA, a:1,
    q:"The Rajiv Gandhi Khel Ratna Awardee receives a cash price of rupees:",
    o:["7.5 lakh","7 lakh","25 lakh","10 lakh"] },
  { orig:55, s:GA, a:1,
    q:"\"A table, a chair, a bowl of fruit and a violin: what else does a man need to be happy?\" is said by:",
    o:["Albert Einstein","Alexander Graham bell","Sir Isaac Newton","Alan Turing"] },
  { orig:56, s:SCI, a:3,
    q:"Compressions and rarefactions are due to variability of:",
    o:["magnetic difference","ray refraction","air pressure","temperature difference"] },
  { orig:57, s:MATH, a:2,
    q:"Tarun and Tapan started a partnership with investments of ₹13,000 and ₹19,500 respectively, however due to a financial emergency Tapan had to withdraw his investment after 8 months. In what ratio should the profit of the first 12 months be shared among the duo?",
    o:["1 : 2","1 : 1","3 : 2","2 : 3"] },
  { orig:58, s:GA, a:4,
    q:"India is the ______ most populated country in the world.",
    o:["fourth","first","third","second"] },
  { orig:60, s:MATH, a:2,
    q:"The volume of sales in a store is recorded for four different quarters — Quarter 1: 200, Quarter 2: 100, Quarter 3: 350, Quarter 4: 550. What are the average sales per quarter?",
    o:["250","300","350","500"] },
  { orig:61, s:REA, a:2,
    q:"Which of the following does NOT belong to the given group?\nA. Tunnel   B. Bunker   C. Well   D. Building",
    o:["B","D","A","C"] },
  { orig:62, s:REA, a:1,
    q:"Jayant introduces a man to his friend as his wife's father's son. The man is Jayant's ______.",
    o:["brother-in-law","sister-in-law","father-in-law","daughter-in-law"] },
  { orig:63, s:SCI, a:1,
    q:"The filtration units in the human kidney are known as ______.",
    o:["nephrons","protons","neurons","neutrons"] },
  { orig:64, s:MATH, a:1,
    q:"Two trains, one 153 m long and the other 127 m long, coming from opposite directions crossed each other in 7.2 seconds. The combined speed of the two trains every hour would then be:",
    o:["140 km/h","105 km/h","70 km/h","280 km/h"] },
  { orig:65, s:SCI, a:2,
    q:"If the chromosome number is 46 in a human being, how many chromosomes are present in somatic cells of the human being?",
    o:["24","46","23","48"] },
  { orig:66, s:MATH, a:1,
    q:"A fraction when added to 7/3 gives 4. The said fraction is:",
    o:["1 2/3","−1/2","2/3","11/2"] },
  { orig:67, s:MATH, a:3,
    q:"4 + 3 × 4 + 3 × 4² + 3 × 4³ + 3 × 4⁴ + 3 × 4⁵ = ?",
    o:["5 × 4⁵","9 × 4⁴","4⁶","10 × 4⁴"] },
  { orig:68, s:GA, a:2,
    q:"Who is the current (as of July 2018) Governor of Reserve Bank of India (RBI)?",
    o:["Arvind Subramanian","Urjit Patel","Amitabh Kant","Raghuram Rajan"] },
  { orig:71, s:SCI, a:3,
    q:"______ is a semiconductor.",
    o:["Ga","Pb","Ge","Sn"] },
  { orig:72, s:MATH, a:3,
    q:"If 3x² + ax + 4 is perfectly divisible by x − 8, then the value of a is:",
    o:["24.5","−25.5","−24.5","25.5"] },
  { orig:73, s:REA, a:2,
    q:"Study the following question and decide which of the statements is/are sufficient to answer the question.\n\nQuestion: What is the total age of Nakul and Dwij?\n\nStatements:\n1. Nakul is 12 years old today.\n2. Dwij is younger to Nakul by 3 years.",
    o:["Statement 1 and 2 together are insufficient","Statements 1 and 2 together are sufficient","Statement 1 alone is sufficient","Statement 2 alone is sufficient"] },
  { orig:74, s:REA, a:4,
    q:"Which of the following does NOT belong to this group?\nA. Poetry   B. Sonnet   C. Rhyme   D. Diagram",
    o:["B","A","C","D"] },
  { orig:76, s:SCI, a:3,
    q:"The electronic configuration of four elements is given below. Which one among the following will be more electronegative?",
    o:["Al (2, 8, 3)","P (2, 8, 5)","Cl (2, 8, 7)","S (2, 8, 6)"] },
  { orig:77, s:MATH, a:4,
    q:"To dispose of the old stocks, a person sold a tea-set for ₹3,540, which was 41% below the cost price. In order to make a profit of 11% the seller should have sold the set for ₹______ more.",
    o:["2664.42","2460","1812.60","3120"] },
  { orig:78, s:GA, a:3,
    q:"Which of the following is the official currency of the European Union?",
    o:["Yen","Dollar","Euro","Pound"] },
  { orig:79, s:MATH, a:2,
    q:"How many of the factors of 512 are perfect squares?",
    o:["3","5","6","4"] },
  { orig:80, s:GA, a:2,
    q:"India celebrates its Constitution Day on:",
    o:["15th December","26th November","21st August","26th January"] },
  { orig:81, s:SCI, a:4,
    q:"An object has a potential energy of 400 J with a mass of 20 kg and gravity 10 N kg⁻¹. The height of the object is:",
    o:["0.5 m","4 m","1 m","2 m"] },
  { orig:82, s:GA, a:4,
    q:"With which sport is B Sai Praneeth associated?",
    o:["Cricket","Kho-Kho","Taekwondo","Badminton"] },
  { orig:83, s:GA, a:2,
    q:"In which of the following field Udipi Ramachandra Rao has been awarded 'Padma Vibhushan' by the Government of India in 2017?",
    o:["Sports","Science","Literature","Music"] },
  { orig:84, s:GA, a:4,
    q:"Which of the below is NOT a city/village/town of Rajasthan?",
    o:["Tonk","Nagaur","Sikar","Navsari"] },
  { orig:85, s:SCI, a:2,
    q:"______ is not acidic.",
    o:["SbCl₄","CCl₄","PCl₄","PCl₃"] },
  { orig:86, s:MATH, a:1,
    q:"A shopkeeper sold two items, one at 25% profit and another at 15% loss and got a profit of ₹35. If the cost price of the item sold at 25% profit is twice that of the item sold at 15% loss, find the sum of the cost price of both items.",
    o:["₹300","₹200","₹100","₹400"] },
  { orig:87, s:REA, a:1,
    q:"What is the next term in the given series?\n22A, 42E, 62I, ?",
    o:["82M","82N","82K","82O"] },
  { orig:88, s:SCI, a:2,
    q:"An object travels 15 m in 4 s and then another 16 m in 3 s. What is the average speed of the object?",
    o:["5.17 ms⁻¹","4.43 ms⁻¹","5.00 s⁻¹","6.17 ms⁻¹"] },
  { orig:89, s:SCI, a:3,
    q:"The law of definite proportions was stated by ______.",
    o:["Democritus","Lavoisier","Proust","John Dalton"] },
  { orig:91, s:GA, a:4,
    q:"The Human Development Index was developed by ______ in 1990.",
    o:["Mahbub Khan","Apara Sen","Syed-ul-Haq","Mahbub-ul-Haq and Amartya Sen"] },
  { orig:92, s:REA, a:2,
    q:"If PIG is coded as 1697, then what will be the code for GOAT?",
    o:["715122","715120","715123","715121"] },
  { orig:93, s:MATH, a:4,
    q:"By what number should 6 2/9 be multiplied to get 40?",
    o:["5 3/7","6","2/9","6 3/7"] },
  { orig:94, s:REA, a:1,
    q:"Leela introduces two girls to her friend as the daughters of the only sister of her father. Leela and the girls are ______.",
    o:["cousins","friends","nieces","twins"] },
  { orig:95, s:REA, a:3,
    q:"Murali takes his dog for a walk. He turns left at a cross road and faces South. Towards which direction was he walking before turning left?",
    o:["East","North","West","South"] },
  { orig:96, s:SCI, a:3,
    q:"A solution turns blue litmus to red, its pH is likely to be ______.",
    o:["9","8","6","7"] },
  { orig:97, s:MATH, a:2,
    q:"If the standard deviation of 0, 1, 2, 3 ... 9 is K, then the standard deviation of 10, 11, 12, 13 ... 19 will be:",
    o:["K+1","K","K+4","K+8"] },
  { orig:98, s:GA, a:2,
    q:"Who was appointed as the new Director General of Military Operations of the Indian Army in 2018?",
    o:["Sarath Chand","Anil Chauhan","Ranbir Singh","A. K. Bhatt"] },
  { orig:99, s:REA, a:3,
    q:"Given is a statement followed by two arguments. Decide which of the arguments is/are strong with respect to the statement.\n\nStatement: There is an increase in mobile usage and cell phone towers.\n\nArguments:\nI. It shows global development and fast and easy way to get connected with the wider world.\nII. In the long run, there will be more signals that will affect the normal functioning of the ecological systems.",
    o:["Neither argument I nor II is strong","Both arguments I and II are strong","Only argument I is strong","Only argument II is strong"] },
  { orig:100, s:MATH, a:4,
    q:"How many balls, each of radius 1 cm, can be made from a steel sphere whose radius is 6 cm?",
    o:["126","27","64","216"] },
];
