// Paper (6 Dec 2018, Shift-1) — English. Source: Adda247 RRB CBT answer-key PDF
// (green-tick = correct option), read via enlarged left-column crops at 300 dpi
// (the dense response-sheet layout needed high res to read tick positions). Kept 88/100.
// Dropped (figure/venn/mirror/count or officially-cancelled "discrepancy", or garbled stem):
//   2,5,28,40,41,52,62,65,71,74,88,97.
const MATH = 'Mathematics';
const REA  = 'General Intelligence & Reasoning';
const SCI  = 'General Science';
const GA   = 'General Awareness & Current Affairs';

export const PART = [
  { orig:1, s:MATH, a:4, q:"6 years ago, a mother's age was 6 times her daughter's age. Three years hence the daughter would be one-third her mother's age. The current age (in years) of the mother is:",
    o:["45","39","36","42"] },
  { orig:3, s:SCI, a:4, q:"Elements in the Modern Periodic Table are arranged in ______ periods.",
    o:["6","8","5","7"] },
  { orig:4, s:SCI, a:2, q:"Plants that have lost their capacity to produce seeds reproduce by the method of:",
    o:["Fission","Vegetative propagation","Multiple fission","Budding"] },
  { orig:6, s:SCI, a:1, q:"What are the organisms that eat other organisms called?",
    o:["Holotrophic organisms","Parasitic organisms","Chemotrophic organisms","Saprotrophic organisms"] },
  { orig:7, s:SCI, a:2, q:"Muscle contains special proteins called ______.",
    o:["lipoproteins","contractile proteins","glyco-proteins","nucleoproteins"] },
  { orig:8, s:SCI, a:2, q:"Heating of ores in the absence of oxygen is called:",
    o:["Extraction","Calcination","Roasting","Corrosion"] },
  { orig:9, s:GA, a:2, q:"Who inaugurated the first edition of Khelo India School Games (KISG) that was held from 31st January to 8th February 2018 at Indira Gandhi Indoor Stadium?",
    o:["The Chief Minister of Delhi","The Prime Minister of India","The Sports Minister","The Home Minister"] },
  { orig:10, s:SCI, a:4, q:"The resistors of values 3 Ω, 6 Ω and 15 Ω are connected in parallel. What will be the equivalent resistance in the circuit?",
    o:["0.8","1.4","2.1","1.7"] },
  { orig:11, s:SCI, a:3, q:"The total quantity of motion contained in the same body is called ______.",
    o:["pressure","force","momentum","inertia"] },
  { orig:12, s:REA, a:4, q:"Read the given statement(s) and conclusions carefully and select which of the conclusions logically follow(s).\n\nStatement: All vitamins are proteins. All proteins are fruits.\n\nConclusions:\n1. Some vitamins are not fruits.\n2. Some fruits are vitamins.",
    o:["Either (1) or (2) follow","Only (1) follows","Both (1) & (2) follow","Only (2) follows"] },
  { orig:13, s:SCI, a:4, q:"The momentum of an object is 50 kg ms⁻¹ and its mass is 10 kg. What is the velocity of the object?",
    o:["5 ms⁻²","0.5 ms⁻²","0.5 ms","5 ms⁻¹"] },
  { orig:14, s:GA, a:2, q:"The book 'My Music, My Life' is the autobiography of:",
    o:["Anushka Shankar","Ravi Shankar","Zakir Hussein","Shankar Mahadevan"] },
  { orig:15, s:REA, a:2, q:"Using the given information, answer the question that follows.\nSix friends are sitting around a circular table.\n1. Soham is sitting adjacent to Nachiket.\n2. Tushar is sitting opposite Pranav.\n3. Swapnil is sitting equidistant to Soham and Pranav.\nWho is sitting opposite Aniket?",
    o:["Nachiket","Soham","Pranav","Swapnil"] },
  { orig:16, s:GA, a:1, q:"Which state of India is the leading producer of coarse cereals?",
    o:["Karnataka","Kerala","Tamilnadu","West Bengal"] },
  { orig:17, s:MATH, a:3, q:"A 173 m long train crosses a 727 m long bridge in 40.5 seconds. What is the speed of the train?",
    o:["70 km/h","85 km/h","80 km/h","75 km/h"] },
  { orig:18, s:GA, a:1, q:"______ is the leading coffee producer state in India.",
    o:["Karnataka","Maharashtra","Telengana","Gujarat"] },
  { orig:19, s:SCI, a:2, q:"The potential energy (P.E.) of a body at a certain height is 200 J. The kinetic energy possessed by the body when it is on the surface of the earth will be:",
    o:["zero","= P.E.","< P.E.","> P.E."] },
  { orig:20, s:SCI, a:2, q:"The spinal cord originates from:",
    o:["Cerebellum","Medulla","Pons","Cerebrum"] },
  { orig:21, s:REA, a:3, q:"Read the given statement(s) and conclusions carefully and select which of the conclusions logically follow(s).\n\nStatement: Increased use of medicines puts down the innate healing sense of the body.\n\nConclusions:\nI. There is an innate healing sense in the body.\nII. Nowadays, we depend more on external medicine and do not allow the body to repair itself.",
    o:["Neither conclusion follows","Both the conclusions follow","Only conclusion I follows","Only conclusion II follows"] },
  { orig:22, s:GA, a:3, q:"The Swadesh Darshan Scheme is an initiative of which ministry?",
    o:["Finance","HRD","Tourism","Defence"] },
  { orig:23, s:MATH, a:3, q:"3/5 th of Sarah's amount is equal to 4/7 th of Priya's amount. Between them the duo has ₹3,570. How much money does Priya have?",
    o:["₹1,540","₹2,100","₹1,470","₹1,400"] },
  { orig:24, s:SCI, a:2, q:"______ meristem is present at the base of the leaves or internodes.",
    o:["Calary","Intercalary","Apical","Lateral"] },
  { orig:25, s:REA, a:3, q:"In a certain code, STAPLE is written as RSZOKD. How is DIGEST written in that code?",
    o:["CHRDFS","CHDFRS","CHFDRS","CHDRFS"] },
  { orig:26, s:MATH, a:4, q:"The ratio of the five angles of a pentagon is 2 : 3 : 4 : 4 : 5. What would be the measure of the largest angle?",
    o:["120°","125°","140°","150°"] },
  { orig:27, s:REA, a:2, q:"Three out of the four options given below are related in a particular way. Choose the option that is different from the others.",
    o:["Cat","Neigh","Frog","Goat"] },
  { orig:29, s:MATH, a:1, q:"If 3x² + ax + 12 is perfectly divisible by x − 3, then the value of a is:",
    o:["−13","−12","−3","−9"] },
  { orig:30, s:SCI, a:1, q:"What will be the mass of mercuric oxide if 92.6 g of mercury reacts with oxygen?",
    o:["100 g","85.2 g","92.6 g","7.4 g"] },
  { orig:31, s:MATH, a:3, q:"The LCM of 88 and 220 is:",
    o:["220","1100","440","880"] },
  { orig:32, s:MATH, a:2, q:"Age of two persons are in the ratio of 5 : 7. 18 years ago, their ages were in the ratio of 8 : 13. What are their present ages?",
    o:["45 & 63 years","50 & 70 years","40 & 80 years","45 & 75 years"] },
  { orig:33, s:MATH, a:4, q:"Insert mathematical symbols in the place of '?' to get the result of the given expression:\n((150 ? 2) ? 2) ? 10 = 87",
    o:["+, ×, ×","+, ÷, ÷","−, ×, ÷","÷, +, +"] },
  { orig:34, s:GA, a:3, q:"How many players were named for Sultan Azlan Shah Cup and Commonwealth Games?",
    o:["11","25","33","22"] },
  { orig:35, s:REA, a:1, q:"P told Q, \"Though I am the son of your father, you are NOT my brother\". How is Q related to P?",
    o:["Sister","Father","Daughter","Son"] },
  { orig:36, s:REA, a:1, q:"If PHONE is written as RJQPG, then WATER can be written as:",
    o:["YCVGT","YVCTG","YVCGT","YCVTG"] },
  { orig:37, s:SCI, a:2, q:"The time period of a vibrating body is 0.05 s. The frequency of waves is:",
    o:["200 Hz","20 Hz","2 Hz","5 Hz"] },
  { orig:38, s:MATH, a:4, q:"132 × 16 ÷ 2³ + 4 = ?",
    o:["792","176","264","268"] },
  { orig:39, s:MATH, a:3, q:"Let n be the number of different 5-digit numbers divisible by 4, formed with the digits 4, 5, 6, 7, 8 and 9, with no digit repeated in the numbers. What is the value of n?",
    o:["8","24","168","192"] },
  { orig:42, s:GA, a:4, q:"What type of a bank is NABARD?",
    o:["Commercial Bank focused on Trade & Industry","Private Bank focused on Technological Development","Cooperative Bank focused on Social and Urban Development","Development Bank focused on Agricultural and Rural Development"] },
  { orig:43, s:GA, a:1, q:"The Brihadisvara Temple was designed by the famous architect:",
    o:["Sama Varma","Ravi Varma","Rama Varma","Govinda"] },
  { orig:44, s:SCI, a:1, q:"A body of mass 100 gm is rotating on a circular path of radius r with constant velocity. The work done in one revolution will be:",
    o:["zero","(100/r) J","100 r J","(r/100) J"] },
  { orig:45, s:REA, a:1, q:"Read the statements and decide whether the conclusion is true or false.\n\nStatements:\n1. Object A is bigger than Q.\n2. Object C is bigger than S.\n\nConclusion: The object S is smaller than Q.",
    o:["Cannot say","Probably false","True","False"] },
  { orig:46, s:GA, a:4, q:"Who among the following has released the 'India 2018' book?",
    o:["Sushma Swaraj","Manohar Parrikar","Narendra Modi","Smriti Irani"] },
  { orig:47, s:SCI, a:4, q:"If the direction of applied force and the direction in which an object moves are perpendicular to each other, then:",
    o:["positive work is done","no power is released","no energy is released","no work is done"] },
  { orig:48, s:SCI, a:2, q:"An object moving with a velocity of 50 ms⁻¹ comes to rest after 20 s. What is its initial velocity?",
    o:["0 ms⁻¹","50 ms⁻¹","0 ms⁻¹","10 ms⁻¹"] },
  { orig:49, s:REA, a:1, q:"Pillow is related to Rest in the same way as Shoes are related to:",
    o:["Run","Fly","Swim","Wear"] },
  { orig:50, s:REA, a:1, q:"Read the given statement(s) and conclusions carefully and select which of the conclusions logically follow(s).\n\nStatement: Due to the rapid increase in the population in developing countries, there is a huge depletion of resources.\n\nConclusions:\nI. The population of developing countries will not continue to increase in future.\nII. It will be very difficult for the governments of developing countries to provide its people with resources.",
    o:["Only conclusion II follows","Neither conclusion I nor II follows","Either conclusion I or II follows","Only conclusion I follows"] },
  { orig:51, s:MATH, a:4, q:"384 ÷ 2⁵ × 3 + 8 = ?",
    o:["12","132","3","44"] },
  { orig:53, s:SCI, a:1, q:"Which is not a correct match of the below?",
    o:["Aldehyde : ----OH","Amides : ----CONH₂","Amines : ---NH₂","Carboxylic Acid : ---COOH"] },
  { orig:54, s:MATH, a:4, q:"A sum of money was divided between A and B in the ratio 17 : 25. If B gave ₹5 to A, the ratio changed. What is the sum of money in question?",
    o:["₹196","₹203","₹217","₹210"] },
  { orig:55, s:REA, a:3, q:"What will be the next term in the below series?\nC3A1, G7E5, ______ ?",
    o:["I8K10","I9K11","K11I9","K10I8"] },
  { orig:56, s:REA, a:2, q:"If North-East becomes North, then what would West become?",
    o:["North-West","South-West","North-East","South-East"] },
  { orig:57, s:GA, a:4, q:"With which of the following sport is Sultan Azlan Shah cup associated?",
    o:["Kabaddi","Foot ball","Tennis","Hockey"] },
  { orig:58, s:REA, a:3, q:"Each question given below consists of a statement, followed by two arguments numbered I and II. Decide which of the arguments is a 'strong' argument.\n\nStatement: Should speed driving be imposed heavy penalties?\n\nArguments:\nI. Yes, speed driving is one of the major causes of road deaths as per statistics.\nII. No, speed driving helps a person to reach his destination soon.",
    o:["Both I and II are strong","Neither I nor II is strong","Only argument I is strong","Only argument II is strong"] },
  { orig:59, s:GA, a:2, q:"Who is the Director of the movie 'Bahubali-2', which was released in 2017?",
    o:["Rajkumar Hirani","S.S. Rajamouli","K. Vishwanath","Sanjay Leela Bhansali"] },
  { orig:60, s:REA, a:2, q:"A statement is followed by two arguments. Decide which of the arguments is/are strong with respect to the statement.\n\nStatement: Government should implement price control on medicines and medical devices.\n\nArguments:\nI. Yes, price control in healthcare has the noble intention of enhancing patient welfare for the people.\nII. No, health care organisations will end up incurring losses or making less margin.",
    o:["Only II is strong","Only I is strong","Neither I nor II is strong","Either I or II is strong"] },
  { orig:61, s:MATH, a:3, q:"Which of the numbers given below is rational?",
    o:["⁶√49","⁶√81","⁶√64","⁶√36"] },
  { orig:63, s:MATH, a:4, q:"Which of the following quadrilaterals has four lines of symmetry?",
    o:["Rhombus","Rectangle","Parallelogram","Square"] },
  { orig:64, s:MATH, a:4, q:"In a computer game a builder can build a wall in 10 hours while a destroyer can demolish such a wall in some hours. Both the builder and the destroyer were initially set to work together on level ground. But after some time the destroyer was taken out. What was the total time (in hours) taken to build the wall?",
    o:["35","17","24","15"] },
  { orig:66, s:REA, a:3, q:"Select the option that is related to the third term in the same way as the second term is related to the first term.\nWall : Brick :: Fabric : ?",
    o:["Brick","Milk","Yarn","Wood"] },
  { orig:67, s:GA, a:3, q:"Who among the following was elected as the Madhya Pradesh Governor?",
    o:["Mamata Banerjee","Mayawati","Anandiben Patel","Aruna Jayanti"] },
  { orig:68, s:MATH, a:1, q:"A solid spherical metal ball of diameter 72 cm is melted and recast into small solid cones. Find the number of cones that can be formed using this melted metal.",
    o:["3,456 cones","3,600 cones","3,568 cones","3,200 cones"] },
  { orig:69, s:REA, a:3, q:"Leela goes for a long drive towards the South. After some time she takes a 90° left turn and then takes a 45° left turn to enter a by-lane. Which direction is Leela heading towards?",
    o:["South-East","South-West","North-East","North-West"] },
  { orig:70, s:MATH, a:3, q:"A rectangle with length 14 cm and width 3 cm is rotated along its length by 150°. What is the volume of the shape generated? (Use π = 22/7)",
    o:["198 cm³","220 cm³","165 cm³","192.5 cm³"] },
  { orig:72, s:SCI, a:4, q:"The image formed by controlled rays of reflection that we get by extending the reflected rays is:",
    o:["Convex","Real","Plain","Virtual"] },
  { orig:73, s:MATH, a:2, q:"The average marks obtained by a group of 25 students was 29. One student left the group as a result of which the average of the remaining students rose to 29.5. Afterwards, another student came in as a result of which the marks of the group dropped to 28.8. What is the average of the combined marks obtained by the student who left and the one who joined?",
    o:["14","14.5","15","13.5"] },
  { orig:75, s:GA, a:3, q:"IPC Section 377, recently in the news, deals about which of the following?",
    o:["Dowry","Divorce","Same sex marriages","Domestic violence"] },
  { orig:76, s:MATH, a:2, q:"Inlet Pipe A can fill a cistern in 35 hours while outlet Pipe B can drain the filled cistern in 40 hours. Both opened together when the cistern is empty; but the outlet pipe is closed when the cistern is three-fourths full. How many hours did it take in all to fill the cistern?",
    o:["185","182","184","180"] },
  { orig:77, s:REA, a:4, q:"Consider the following question and decide which of the statements is sufficient to answer the question.\n\nQuestion: Find the value of n.\n\nStatements:\n1. AB = A\n2. A = [[n, 9], [2, 1]], B = [[1, 0], [0, 1]]",
    o:["Only 1 is sufficient","Only 2 is sufficient","Either 1 or 2 is sufficient","Both 1 and 2 are NOT sufficient"] },
  { orig:78, s:MATH, a:1, q:"A and B can do a piece of work together in 9 days while A alone can do it in 15 days. They start working together but A leaves 3 days before the completion of the work. For how many days did A and B work together?",
    o:["7.2","7.5","8.1","8"] },
  { orig:79, s:MATH, a:2, q:"35 : 98 :: x : 140. What is the value of x?",
    o:["60","50","55","65"] },
  { orig:80, s:MATH, a:3, q:"The following table shows the pass percentage of results of four schools — School / 2012-13 / 2013-14 / 2014-15 / 2015-16: XYZ 78, 69, 81, 92; ABC 61, 72, 84, 96; PQR 81, 92, 85, 97; TUV 92, 69, 72, 95. In which academic year did all the schools have pass percentage of more than 90%?",
    o:["2012-13","2014-15","2015-16","2013-14"] },
  { orig:81, s:GA, a:2, q:"Rabindranath Tagore received the Nobel prize for Literature in 1913 for his work:",
    o:["Gora","Gitanjali","The Home and The World","Grain of Sand"] },
  { orig:82, s:GA, a:4, q:"Bahadur Shah, the last Mughal Emperor, was exiled to ______ for fear of revolt.",
    o:["Mysore","Carnatic","Awadh","Burma"] },
  { orig:83, s:GA, a:2, q:"Who is the author of the book 'One Indian Girl'?",
    o:["Amit Chauduri","Chetan Bhagat","Vikram Chandra","Vikram Seth"] },
  { orig:84, s:REA, a:4, q:"Two friends enter a restaurant that has an entrance facing East. They were asked to take right and then a turn to occupy the seats. Which direction did they turn after entering the restaurant to occupy the seats?",
    o:["East","West","South","North"] },
  { orig:85, s:MATH, a:4, q:"The LCM of 76 and 57 is:",
    o:["114","171","152","228"] },
  { orig:86, s:REA, a:1, q:"If North becomes North-East then what will North-East become?",
    o:["East","West","North","South"] },
  { orig:87, s:SCI, a:3, q:"Which of the below devices does not use integrated circuit?",
    o:["Mobile phones","Computer","Camera","Television"] },
  { orig:89, s:SCI, a:3, q:"What is 'amu' in the context of atoms and molecules?",
    o:["Avegadro Mass Unit","Atomic Unified Mass Unit","Atomic Mass Unit","Atomic Molecule Unit"] },
  { orig:90, s:SCI, a:3, q:"Bleaching powder is produced by the action of chlorine on dry slaked lime. Which of the following is the equation for this?",
    o:["Ca(OH)₂ + 2Cl = CaOCl₂ + H₂O","Ca(OH)₂ + Cl₂ = 2CaOCl₂ + H₂O","Ca(OH)₂ + Cl₂ = CaOCl₂ + H₂O","Ca(OH)₂ + Cl₂ = CaOCl₂ + 2H₂O"] },
  { orig:91, s:GA, a:1, q:"Who is the present Comptroller and Auditor General of India?",
    o:["Rajiv Mehrishi","Amitabh Kant","Shashikanth Sharma","Mukul Rohatgi"] },
  { orig:92, s:GA, a:4, q:"Who among the following was the Prime Minister of India when Mandal Commission was set up?",
    o:["Manmohan Singh","Atal Bihari Vajpayee","VP Singh","Morarji Desai"] },
  { orig:93, s:MATH, a:3, q:"Find the remainder when 1 + a + a² + a³ + ... + a²⁰¹⁸ is divided by (a − 1).",
    o:["2018","2017","2019","0"] },
  { orig:94, s:MATH, a:3, q:"If 8ˣ = 4/2ˣ, then find x.",
    o:["1","2","1/2","2/3"] },
  { orig:95, s:GA, a:1, q:"Which of the following is NOT a Fundamental Right provided in the Indian Constitution?",
    o:["Right to Property","Right to Education","Right to Freedom","Right to Equality"] },
  { orig:96, s:SCI, a:1, q:"We all know from our observation that water can exist in three states.\nStatements:\nA. Solid, as ice.\nB. Liquid, as petrol.\nC. Gas, as O₂.\nWhich of the following statements is/are true?",
    o:["Only A is true, B and C are false","A and B are true, C is false","All are false","All are true"] },
  { orig:98, s:MATH, a:4, q:"5/7 of a number is 2/3. What is the number?",
    o:["15/14","15/7","7/15","14/15"] },
  { orig:99, s:REA, a:3, q:"What is the next term in this series?\n22, 18, 40, 48, 58, ______",
    o:["90","70","78","68"] },
  { orig:100, s:GA, a:1, q:"There are ______ parallel ranges of the Himalayas.",
    o:["three","two","five","four"] },
];
