// RRB Group D — 22 Sep 2018 Shift-1 (English). Dense CBT response-sheet source (CEN-02/2018).
// Answer = GREEN-TICK option (NOT candidate "Chosen Option"). Kept 85/100. Dropped figure/chart/cancelled Qs.
const MATH = 'Mathematics';
const REA  = 'General Intelligence & Reasoning';
const SCI  = 'General Science';
const GA   = 'General Awareness & Current Affairs';

export const PART = [
  { orig:2,  s:GA,   a:1, q:"Who among the following has been conferred the National Kalidas Samman award in 2018?", o:["Anjolie Ela Menon","Girish Karnad","Mallika Sarabhai","Shabana Azmi"] },
  { orig:3,  s:SCI,  a:4, q:"The chemical formula of Iron (III) oxide is ______.", o:["FeO","Fe₃O₄","Fe₃O₃","Fe₂O₃"] },
  { orig:4,  s:REA,  a:3, q:"Find the odd man out: Si, P, Ge, and As", o:["Si","As","P","Ge"] },
  { orig:5,  s:MATH, a:2, q:"The sum of the first 2007 terms of the sequence 1, 2, 3, 4, 1, 2, 3, 4, ______ is:", o:["5013","5016","5020","5107"] },
  { orig:6,  s:MATH, a:2, q:"₹ 1,125 invested for 3 months gave an interest of ₹ 27. What was the simple rate of interest per annum?", o:["12%","9.6%","7.2%","2.4%"] },
  { orig:7,  s:GA,   a:3, q:"Which union ministry has launched nation-wide training programme for Elected Women Representatives (EWRs) of Panchayats?", o:["Ministry of Panchayati Raj","Ministry of External Affairs","Ministry of Women and Child Development","Ministry of Culture"] },
  { orig:9,  s:GA,   a:4, q:"Where is 'The Gateway of India' located?", o:["Chennai","Jaipur","New Delhi","Mumbai"] },
  { orig:10, s:MATH, a:1, q:"A mobile when sold at a gain of 6% yields ₹ 870 more than when it is sold at a loss of 6%. What is the cost price of the mobile phone?", o:["₹ 7250","₹ 6265","₹ 6000","₹ 7000"] },
  { orig:11, s:MATH, a:2, q:"A 1.5 m tall boy observes a pole. The angle of elevation of the top of the pole is 30° from the eyes of the boy. Then he approaches the pole by 7.3 m. Now the angle of elevation is 45°. Find the height of the pole from the ground. Take √3 = 1.73", o:["8.5 m","11.5 m","10 m","11 m"] },
  { orig:12, s:SCI,  a:3, q:"According to Whittaker's classification, organisms belonging to the kingdom ______ do not have a well defined nucleus.", o:["Protista","Fungi","Monera","Plantae"] },
  { orig:14, s:SCI,  a:1, q:"A current of 0.5 A is maintained in a resistor of 10 Ω. The amount of charge flowing through the resistor in one minute is:", o:["30 C","5 C","0.5 C","20 C"] },
  { orig:15, s:MATH, a:1, q:"The time taken for the tail end of a train to cross a pole is 53 seconds. If the length of the train is 110 m and speed of the train is 36 km/hr, find the initial distance of the pole from the front end of the train.", o:["420 m","530 m","640 m","1798 m"] },
  { orig:16, s:MATH, a:3, q:"Find the 13/16 worth of land whose 9/7 worth is ₹ 10116.", o:["₹ 6391.75","₹ 6394.75","₹ 6392.75","₹ 6302.75"] },
  { orig:17, s:MATH, a:2, q:"Shaan's current age is four years less than 1.6 times that of Uddalak's. 26 years ago, Uddalak's age was one year less than half of Shaan's age. What is Shaan's present age in years?", o:["84","76","68","60"] },
  { orig:18, s:GA,   a:2, q:"The mega event Global Entrepreneurship Summit (GES-2017) in Hyderabad was co-hosted by NITI Aayog. What is the full form of NITI?", o:["Nation Institute Teaching India","National Institution for Transforming India","National India Transforming Information","National Institution Towards India"] },
  { orig:19, s:REA,  a:1, q:"If \"LAME\" is coded as JYKC, how \"MINE\" would be written in this code?", o:["KGLC","KHGC","KLGC","KJGC"] },
  { orig:20, s:SCI,  a:3, q:"If an electric iron rated 1000W is operated for 3 hours/day, find the total energy consumed in 30 days in kWh.", o:["90000","9000","90","900"] },
  { orig:21, s:MATH, a:1, q:"70 ÷ 5 × (10 − 8 ÷ 2) ÷ 3 = ?", o:["28","3","1/3","7"] },
  { orig:22, s:SCI,  a:1, q:"Frictional force acts ______.", o:["Against the direction of the force","At any angle to the direction of the force","In the direction of the force","Perpendicular to the direction of the force"] },
  { orig:23, s:REA,  a:3, q:"Can you tell which argument is strong? Statement: Should government take priority linking rivers? Arguments: I. Yes, in the long run this will entirely eradicate water shortages in remote areas. II. No, we shouldn't contaminate water and the rivers will naturally take its course.", o:["Both I and II are strong","Only argument II is strong","Only argument I is strong","Only argument II is strong"] },
  { orig:24, s:SCI,  a:4, q:"The elements with atomic numbers 35, 53 and 85 are ______.", o:["noble gases","halides","alkaline","halogens"] },
  { orig:26, s:REA,  a:2, q:"Find the odd one out: W23, I10, L12, Q17", o:["W23","I10","L12","Q17"] },
  { orig:27, s:MATH, a:4, q:"If the perimeter of a circular plot is equal to that of a square plot, then the ratio of their respective areas is:", o:["6 : 11","7 : 11","12 : 11","14 : 11"] },
  { orig:29, s:SCI,  a:3, q:"The mass number of an isotope of an element is 298. If its nucleus has 189 neutrons, what is its atomic number?", o:["487.0","189.0","109.0","298.0"] },
  { orig:30, s:MATH, a:2, q:"In a triangle ABC, points D and E are lying on AB and AC, respectively. DE is also parallel to the base BC. O is the intersection of BE and CD. If AD : DB = 4 : 3 find the ratio of DO to DC.", o:["5 : 7","4 : 11","5 : 12","3 : 7"] },
  { orig:31, s:MATH, a:3, q:"Three flood gates A, B and C can fill a reservoir in 6 hours. After working at it together for 2 hours, flood gate C is closed. Flood gates A and B can fill the remaining part in 7 hours. The number of hours taken by flood gate C alone to fill the reservoir is:", o:["16","10","14","12"] },
  { orig:32, s:GA,   a:4, q:"Ace Indian cueist ______ won the 2017 IBSF World Billiards Championship held at Doha.", o:["Ashok Shandilya","Subhash Agarwal","Geet Sethi","Pankaj Advani"] },
  { orig:33, s:GA,   a:3, q:"Who among the following has been appointed the Chef de Mission of the Indian contingent for the Asian Games 2018?", o:["Ramkishore Singh","Rajeev Mehta","Brij Bhushan Sharan Singh","Dig Vijay Singh"] },
  { orig:34, s:SCI,  a:2, q:"Odometer is an instrument used to measure:", o:["Direction","Distance","Odour","Speed"] },
  { orig:38, s:SCI,  a:4, q:"The hydrochloric acid secreted by the gastric glands facilitates the action of the enzyme ______.", o:["Amylase","Trypsin","Lipase","Pepsin"] },
  { orig:39, s:REA,  a:3, q:"If '+' means '−', '−' means '×', '÷' means '+' and '×' means '÷', then what is the value of 23 − 4 + 15 × 3 ÷ 10 ?", o:["110","95","97","100"] },
  { orig:40, s:REA,  a:1, q:"If TEEN is written as 205514, then what is code for ENTER?", o:["51420518","51520618","51420618","51520518"] },
  { orig:41, s:SCI,  a:3, q:"When a bullet is fired from a gun the kinetic energy of the bullet is ______.", o:["Less than the gun","Is uncomparable","More than the gun","Equal to the gun"] },
  { orig:42, s:MATH, a:3, q:"The square root of 13.69 is ______.", o:["0.37","0.037","3.7","37"] },
  { orig:43, s:GA,   a:3, q:"Which actor's autobiography is titled as 'Khullam Khulla'?", o:["Ranbir Kapoor","Raj Kapoor","Rishi Kapoor","Rajiv Kapoor"] },
  { orig:45, s:SCI,  a:3, q:"A truck falls off a ledge and drops to the ground in 0.8 secs. How high is the ledge from the ground? (g = 10 m/s²)", o:["0.32m","320m","3.2m","32m"] },
  { orig:46, s:MATH, a:1, q:"The HCF of 54, 66 and 90 is:", o:["6","9","4","3"] },
  { orig:47, s:REA,  a:4, q:"Given is a statement followed by two arguments numbered I and II. Consider the statement and the arguments and decide which of the arguments is/are strong. Statement: Are games to be made compulsory for primary students? Arguments: I. Yes, games are important for physical development. II. No, games waste the academic time of the students, thus making them weaker in academics.", o:["Both argument I and II are strong","Only argument II is strong","Neither argument I nor II is strong","Only argument I is strong"] },
  { orig:48, s:GA,   a:4, q:"Who was the first female CEO of Lloyd's of London?", o:["Deanna M. Mulligan","Beth E. Mooney","Anna Manning","Inga Beale"] },
  { orig:49, s:REA,  a:2, q:"Using the below statements can we verify the conclusions? Statement: All diagrams are figures; All figures are three dimensions. Conclusions: 1. All three dimensions are diagrams; 2. All figures are diagrams.", o:["All the conclusions follow","No conclusion follow","Only conclusion 1 follows","Only conclusion 2 follows"] },
  { orig:50, s:SCI,  a:2, q:"The process where electricity is passed through 10% NaCl is called ______.", o:["Hall – Heroult process","Chlor-alkali process","Bayers process","Chlor-salt process"] },
  { orig:51, s:SCI,  a:4, q:"Name three elements that have a Single electron outermost Shells?", o:["Magnesium, Helium, Neon","Magnesium, Calcium, Barium","Helium, Neon, Argon","Lithium, Sodium, Potassium"] },
  { orig:52, s:GA,   a:2, q:"The Pulichintala Hydroelectric Project is on which river?", o:["Penna","Krishna","Kaveri","Godavari"] },
  { orig:53, s:MATH, a:3, q:"5.52 − 2.3² + 0.8³ × 0.12 ÷ 0.4⁴ − 3.14 = ?", o:["0.42","0.51","−0.51","−0.63"] },
  { orig:54, s:SCI,  a:3, q:"Solution A has a pH of 6, Solution B has a pH of 8 and Solution C has a pH of 2, which solution has the most hydrogen ion concentration?", o:["B","A","C","None have hydrogen ions"] },
  { orig:55, s:REA,  a:3, q:"Find the next number in the following series. 10, 16, 25, 37, ?", o:["42","50","52","45"] },
  { orig:56, s:GA,   a:1, q:"Who inaugurated Global Entrepreneurship Summit (GES-2017) in Hyderabad jointly with PM Narendra Modi?", o:["Ivanka Trump","Ivana Trump","Melanie Trump","Donald Trump"] },
  { orig:57, s:MATH, a:3, q:"The mean of the observations x, x + 3, x + 5, x + 8, x + 9 is 9. What is the mean of the last three observations?", o:["31/3","32/3","34/3","35/3"] },
  { orig:58, s:REA,  a:2, q:"Sumana introduces Mahesh and Kumresh as her son's uncle's sons. The boys are Sumana's ______.", o:["friends","nephews","cousins","nieces"] },
  { orig:59, s:GA,   a:3, q:"Which state government will set up the world's first IT campus for differently-abled persons?", o:["Haryana","Andhra Pradesh","Telangana","West Bengal"] },
  { orig:60, s:MATH, a:4, q:"Raghuvir obtained an average of 25 marks in 12 tests. Rumela has been maintaining an average of 23 marks so far, but she has taken only 8 of the tests. How much does Rumela have to score on an average in the remaining 4 tests to match Raghuvir's performance?", o:["26","28","27","29"] },
  { orig:61, s:SCI,  a:1, q:"The oxides of carbon, nitrogen and Sulphur that are released on burning fossil fuels are ______.", o:["Acidic oxides","Neutral oxides","Amphoteric oxides","Basic oxides"] },
  { orig:62, s:SCI,  a:4, q:"Two bones can be connected to each other by another type of connective tissue called the ______.", o:["Tendons","Cartilage","Matrix","Ligament"] },
  { orig:63, s:MATH, a:3, q:"By working 8 hours a day, Ram writes a book in 18 days. How many hours should he work per day to complete this work in 12 days?", o:["9 hours","10 hours","12 hours","15 hours"] },
  { orig:64, s:GA,   a:1, q:"Who among the following was appointed as a whole-time member of market regulator Securities and Exchange Board of India (SEBI) on 7 November 2017?", o:["Sanjeev Kaushik","U.K. Sinha","Neelam Damodaran","V. Ramakrishnan"] },
  { orig:65, s:REA,  a:1, q:"Suresh is facing the south-west direction. He turns 135° clockwise and then turns 45° in the anti-clockwise direction. Which direction is he facing now?", o:["North-West","South","North-East","North"] },
  { orig:66, s:GA,   a:3, q:"Who amongst the following won the Best FIFA Men's Player Award 2017?", o:["Lionel Messi","Neymar Jr.","Cristiano Ronaldo","Wayne Rooney"] },
  { orig:67, s:GA,   a:2, q:"Who was the founder of the Pratihara dynasty?", o:["Narasimhadeva I","Harishchandra","Harshvardhan","Ramachandra"] },
  { orig:69, s:SCI,  a:2, q:"The element with atomic number 57 belongs to:", o:["s-block","d-block","f-block","p-block"] },
  { orig:70, s:GA,   a:2, q:"Aihole Inscription is associated with which of the following rulers?", o:["Vikramaditya","Pulakesin II","Akbar","Ashoka"] },
  { orig:71, s:MATH, a:3, q:"There are a red, b yellow and c green tokens in a bag. If a : b :: 13 : 10, b : c :: 6 : 13, then a : b : c is given by:", o:["13 : 6 : 10","13 : 6 : 13","39 : 30 : 65","13 : 60 : 13"] },
  { orig:73, s:SCI,  a:2, q:"The dehydrating agent used in the conversion of ethanol to ethene is ______.", o:["Heat","Concentrated Sulphuric acid","Nickel","Sunlight"] },
  { orig:74, s:GA,   a:1, q:"In which state is the oldest oil field of India?", o:["Assam","Punjab","Maharashtra","Gujarat"] },
  { orig:75, s:REA,  a:2, q:"Find the next term in this series. 14, 42, 126, ______.", o:["370","378","376","375"] },
  { orig:76, s:REA,  a:3, q:"Saraswathi and Gauri are sisters. How is Gauri's brother related to Saraswathi's father's father?", o:["Grand-daughter","Uncle","Grandson","Son"] },
  { orig:77, s:REA,  a:3, q:"What day would it be on 29th March 2020?", o:["Friday","Monday","Sunday","Saturday"] },
  { orig:78, s:GA,   a:1, q:"Who was the second Indian women footballer to win the Arjuna Award?", o:["Oinam Bembem Devi","Aditi Chauhan","Bala Devi","Mithali Raj"] },
  { orig:79, s:REA,  a:2, q:"Given is a statement followed by two assumptions numbered I and II. Consider the statement and the following assumptions and decide which of the assumptions is/are implicit in the statement. Statement: \"One of the reasons of obesity is binging on junk food\", says a mom to her daughter. Assumptions: I. Junk food causes obesity. II. Rita and Gita are mom and daughter.", o:["Both assumptions I and II are implicit","Only assumption I is implicit","Only assumption II is implicit","Neither assumption I nor II is implicit"] },
  { orig:80, s:MATH, a:1, q:"Rakesh and Ranjit can complete a task in 4 and 6 days, respectively when working alone. Ranjit started working on the task, and was joined by Rakesh after 2 days. How many days will they require to complete the remaining work?", o:["1.6","0.8","2","1.2"] },
  { orig:81, s:MATH, a:4, q:"A ladder of length 13 metres is placed against the wall and the foot of the ladder is 6.5 metres from the wall. What is the angle of elevation of the ladder leaning against a wall?", o:["105°","30°","45°","60°"] },
  { orig:82, s:MATH, a:3, q:"How many leap years are there in a period of 100 years?", o:["23","22","24","25"] },
  { orig:83, s:GA,   a:2, q:"What is the GDP growth rate for India in 2018-19 projected by IMF?", o:["8.5%","7.3%","9%","6%"] },
  { orig:84, s:REA,  a:3, q:"Which assumptions are implied from the below statement? The headmistress called for a meeting for all parents and teaching staff to discuss fee structure. Assumptions: I. There is a plan to revamp fee structure. II. To arrive at a common consent.", o:["Only II is implicit","Only I is implicit","Both I and II are implicit","Neither I nor II is implicit"] },
  { orig:85, s:REA,  a:4, q:"In the series below one of the sequence is wrong. Find out the wrong option:", o:["2000400000","400000600000008","100300005","300040006"] },
  { orig:86, s:GA,   a:3, q:"Who is the first chief commercial officer (CCO) of Bajaj Auto Ltd.?", o:["Ramesh Maheshwari","Sumeet Narang","Rakesh Sharma","Eric Vas"] },
  { orig:87, s:MATH, a:2, q:"If (x + y) : (x − y) = 5 : 1 then (x² + y²) : (x² − y²) = ?", o:["8 : 17","13 : 5","25 : 9","16 : 1"] },
  { orig:88, s:SCI,  a:3, q:"The tissue providing nutrition to the embryo in the uterus is the ______.", o:["Fallopian tube","Oviduct","Placenta","Villi"] },
  { orig:89, s:MATH, a:3, q:"The cost of same valued 15 tickets is ₹ 9. What will be the cost of 30 tickets?", o:["₹ 19","₹ 15","₹ 18","₹ 16"] },
  { orig:91, s:MATH, a:2, q:"The compound interest on ₹ 31250 at 8% per annum for 2 3/4 years is?", o:["₹ 7337","₹ 7387","₹ 7800","₹ 7300"] },
  { orig:92, s:SCI,  a:2, q:"______ never occurs singly in nature.", o:["Momentum","Force","Velocity","Pressure"] },
  { orig:94, s:SCI,  a:1, q:"______ can reproduce by budding.", o:["Hydra","Earthworms","Lobsters","Starfish"] },
  { orig:96, s:GA,   a:2, q:"Who was the Chairman of the Drafting committee of Indian Constitution?", o:["Jawaharlal Nehru","Dr. B.R. Ambedkar","Vallabhai Patel","Dr. Rajendra Prasad"] },
  { orig:98, s:SCI,  a:1, q:"The size of the image formed by a converging mirror when object is placed at principal focus is ______.", o:["highly magnified","diminished","of the same size","point image"] },
  { orig:99, s:REA,  a:4, q:"Read the given statement(s) and conclusions carefully and select which of the conclusions logically follow(s) from the statement(s). Statement: All wool are yarn; Some wool are rough. Conclusions: I. All rough are wool; II. Some yarn are rough.", o:["Both conclusions follow","Only conclusion I follows","Neither I nor II follows","Only conclusion II follows"] },
  { orig:100,s:SCI,  a:3, q:"A galvanometer is used to:", o:["detect the direction of light","detect the direction of sound","detect the direction of current","detect the direction of magnetic induction"] },
];
