import { NextResponse } from 'next/server';
import dbConnect from '@/lib/db';
import DailyChallenge from '@/models/DailyChallenge';
import Question from '@/models/Question';
import { protect, admin } from '@/middleware/auth';

// POST - Auto-generate daily challenge from question bank
export async function POST(req) {
    try {
        const auth = await protect(req);
        if (!auth.authenticated || !admin(auth.user)) {
            return NextResponse.json({ message: 'Admin access required' }, { status: 403 });
        }
        await dbConnect();
        const { date, count = 10, difficulty = 'mixed' } = await req.json();

        const targetDate = new Date(date || new Date());
        targetDate.setHours(0, 0, 0, 0);

        // Check if challenge already exists for this date
        const existing = await DailyChallenge.findOne({
            date: { $gte: targetDate, $lt: new Date(targetDate.getTime() + 86400000) }
        });
        if (existing) return NextResponse.json({ message: 'Challenge already exists for this date', data: existing }, { status: 400 });

        // Pick random questions
        let query = { isActive: true };
        if (difficulty !== 'mixed') query.difficulty = difficulty;

        const questions = await Question.aggregate([
            { $match: query },
            { $sample: { size: count } }
        ]);

        if (questions.length === 0) {
            return NextResponse.json({ message: 'No questions available in question bank' }, { status: 400 });
        }

        const challengeQuestions = questions.map(q => ({
            questionText: q.questionText,
            options: q.options,
            explanation: q.explanation || '',
            subject: q.subject?.toString() || '',
            difficulty: q.difficulty
        }));

        const challenge = await DailyChallenge.create({
            date: targetDate,
            title: `Daily Challenge - ${targetDate.toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`,
            questions: challengeQuestions,
            duration: count,
            totalMarks: count,
            isAutoGenerated: true,
            status: 'published'
        });

        return NextResponse.json({ success: true, data: challenge }, { status: 201 });
    } catch (error) {
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
