import mongoose from 'mongoose';

const dailyChallengeSchema = new mongoose.Schema({
    date: { type: Date, required: true, unique: true },
    title: { type: String, required: true, trim: true },
    exam: { type: mongoose.Schema.Types.ObjectId, ref: 'Exam' },
    questions: [{
        questionText: { type: String, required: true },
        options: [{
            text: { type: String, required: true },
            isCorrect: { type: Boolean, default: false }
        }],
        explanation: { type: String, default: '' },
        subject: { type: String, default: '' },
        difficulty: { type: String, enum: ['easy', 'medium', 'hard'], default: 'medium' }
    }],
    duration: { type: Number, default: 10 },
    totalMarks: { type: Number, default: 10 },
    totalAttempts: { type: Number, default: 0 },
    avgScore: { type: Number, default: 0 },
    isAutoGenerated: { type: Boolean, default: false },
    status: { type: String, enum: ['draft', 'published', 'archived'], default: 'published' }
}, { timestamps: true });

dailyChallengeSchema.index({ date: -1 }, { unique: true });
dailyChallengeSchema.index({ status: 1, date: -1 });

export default mongoose.models.DailyChallenge || mongoose.model('DailyChallenge', dailyChallengeSchema);
